/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type { CentrifugoTokenResponse, ResultObject } from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type tokenResponse200 = {
  data: CentrifugoTokenResponse;
  status: 200;
};

export type tokenResponse400 = {
  data: ResultObject;
  status: 400;
};

export type tokenResponse405 = {
  data: ResultObject;
  status: 405;
};

export type tokenResponse500 = {
  data: ResultObject;
  status: 500;
};

export type tokenResponseSuccess = tokenResponse200 & {
  headers: Headers;
};
export type tokenResponseError = (
  | tokenResponse400
  | tokenResponse405
  | tokenResponse500
) & {
  headers: Headers;
};

export type tokenResponse = tokenResponseSuccess | tokenResponseError;

export const getTokenUrl = () => {
  return `/api/userWallet/centrifugo/token`;
};

/**
 * @summary 获取 Centrifugo 连接 token
 */
export const token = async (options?: RequestInit): Promise<tokenResponse> => {
  return appAxiosInstance<tokenResponse>(getTokenUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getTokenQueryKey = () => {
  return [`/api/userWallet/centrifugo/token`] as const;
};

export const getTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTokenQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof token>>> = ({
    signal,
  }) => token({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof token>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TokenQueryResult = NonNullable<Awaited<ReturnType<typeof token>>>;
export type TokenQueryError = ResultObject;

export function useToken<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof token>>,
          TError,
          Awaited<ReturnType<typeof token>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useToken<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof token>>,
          TError,
          Awaited<ReturnType<typeof token>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useToken<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 获取 Centrifugo 连接 token
 */

export function useToken<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTokenQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getTokenSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTokenQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof token>>> = ({
    signal,
  }) => token({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof token>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TokenSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof token>>
>;
export type TokenSuspenseQueryError = ResultObject;

export function useTokenSuspense<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTokenSuspense<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTokenSuspense<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 获取 Centrifugo 连接 token
 */

export function useTokenSuspense<
  TData = Awaited<ReturnType<typeof token>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof token>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTokenSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
