/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  AppleIapVerifyRequest,
  AppleIapWebhookRequest,
  GooglePlayVerifyRequest,
  GooglePlayWebhookRequest,
  IapCreateOrderRequest,
  IapOrderResponse,
  IapVerifyResponse,
  ResultObject,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createOrderResponse200 = {
  data: IapOrderResponse;
  status: 200;
};

export type createOrderResponse400 = {
  data: ResultObject;
  status: 400;
};

export type createOrderResponse405 = {
  data: ResultObject;
  status: 405;
};

export type createOrderResponse500 = {
  data: ResultObject;
  status: 500;
};

export type createOrderResponseSuccess = createOrderResponse200 & {
  headers: Headers;
};
export type createOrderResponseError = (
  | createOrderResponse400
  | createOrderResponse405
  | createOrderResponse500
) & {
  headers: Headers;
};

export type createOrderResponse =
  | createOrderResponseSuccess
  | createOrderResponseError;

export const getCreateOrderUrl = () => {
  return `/api/userWallet/iap/orders`;
};

/**
 * @summary Create an Apple or Google IAP order
 */
export const createOrder = async (
  iapCreateOrderRequest: IapCreateOrderRequest,
  options?: RequestInit,
): Promise<createOrderResponse> => {
  return appAxiosInstance<createOrderResponse>(getCreateOrderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(iapCreateOrderRequest),
  });
};

export const getCreateOrderMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOrder>>,
    TError,
    { data: IapCreateOrderRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOrder>>,
  TError,
  { data: IapCreateOrderRequest },
  TContext
> => {
  const mutationKey = ['createOrder'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOrder>>,
    { data: IapCreateOrderRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createOrder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOrder>>
>;
export type CreateOrderMutationBody = IapCreateOrderRequest;
export type CreateOrderMutationError = ResultObject;

/**
 * @summary Create an Apple or Google IAP order
 */
export const useCreateOrder = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOrder>>,
      TError,
      { data: IapCreateOrderRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createOrder>>,
  TError,
  { data: IapCreateOrderRequest },
  TContext
> => {
  return useMutation(getCreateOrderMutationOptions(options), queryClient);
};
export type googleWebhookResponse200 = {
  data: IapVerifyResponse;
  status: 200;
};

export type googleWebhookResponse400 = {
  data: ResultObject;
  status: 400;
};

export type googleWebhookResponse405 = {
  data: ResultObject;
  status: 405;
};

export type googleWebhookResponse500 = {
  data: ResultObject;
  status: 500;
};

export type googleWebhookResponseSuccess = googleWebhookResponse200 & {
  headers: Headers;
};
export type googleWebhookResponseError = (
  | googleWebhookResponse400
  | googleWebhookResponse405
  | googleWebhookResponse500
) & {
  headers: Headers;
};

export type googleWebhookResponse =
  | googleWebhookResponseSuccess
  | googleWebhookResponseError;

export const getGoogleWebhookUrl = (key: string) => {
  return `/api/userWallet/iap/google/webhook/${key}`;
};

export const googleWebhook = async (
  key: string,
  googlePlayWebhookRequest: GooglePlayWebhookRequest,
  options?: RequestInit,
): Promise<googleWebhookResponse> => {
  return appAxiosInstance<googleWebhookResponse>(getGoogleWebhookUrl(key), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(googlePlayWebhookRequest),
  });
};

export const getGoogleWebhookMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof googleWebhook>>,
    TError,
    { key: string; data: GooglePlayWebhookRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof googleWebhook>>,
  TError,
  { key: string; data: GooglePlayWebhookRequest },
  TContext
> => {
  const mutationKey = ['googleWebhook'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof googleWebhook>>,
    { key: string; data: GooglePlayWebhookRequest }
  > = (props) => {
    const { key, data } = props ?? {};

    return googleWebhook(key, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoogleWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof googleWebhook>>
>;
export type GoogleWebhookMutationBody = GooglePlayWebhookRequest;
export type GoogleWebhookMutationError = ResultObject;

export const useGoogleWebhook = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof googleWebhook>>,
      TError,
      { key: string; data: GooglePlayWebhookRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof googleWebhook>>,
  TError,
  { key: string; data: GooglePlayWebhookRequest },
  TContext
> => {
  return useMutation(getGoogleWebhookMutationOptions(options), queryClient);
};
export type verifyGoogleResponse200 = {
  data: IapVerifyResponse;
  status: 200;
};

export type verifyGoogleResponse400 = {
  data: ResultObject;
  status: 400;
};

export type verifyGoogleResponse405 = {
  data: ResultObject;
  status: 405;
};

export type verifyGoogleResponse500 = {
  data: ResultObject;
  status: 500;
};

export type verifyGoogleResponseSuccess = verifyGoogleResponse200 & {
  headers: Headers;
};
export type verifyGoogleResponseError = (
  | verifyGoogleResponse400
  | verifyGoogleResponse405
  | verifyGoogleResponse500
) & {
  headers: Headers;
};

export type verifyGoogleResponse =
  | verifyGoogleResponseSuccess
  | verifyGoogleResponseError;

export const getVerifyGoogleUrl = () => {
  return `/api/userWallet/iap/google/verify`;
};

export const verifyGoogle = async (
  googlePlayVerifyRequest: GooglePlayVerifyRequest,
  options?: RequestInit,
): Promise<verifyGoogleResponse> => {
  return appAxiosInstance<verifyGoogleResponse>(getVerifyGoogleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(googlePlayVerifyRequest),
  });
};

export const getVerifyGoogleMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyGoogle>>,
    TError,
    { data: GooglePlayVerifyRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof verifyGoogle>>,
  TError,
  { data: GooglePlayVerifyRequest },
  TContext
> => {
  const mutationKey = ['verifyGoogle'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof verifyGoogle>>,
    { data: GooglePlayVerifyRequest }
  > = (props) => {
    const { data } = props ?? {};

    return verifyGoogle(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type VerifyGoogleMutationResult = NonNullable<
  Awaited<ReturnType<typeof verifyGoogle>>
>;
export type VerifyGoogleMutationBody = GooglePlayVerifyRequest;
export type VerifyGoogleMutationError = ResultObject;

export const useVerifyGoogle = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof verifyGoogle>>,
      TError,
      { data: GooglePlayVerifyRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof verifyGoogle>>,
  TError,
  { data: GooglePlayVerifyRequest },
  TContext
> => {
  return useMutation(getVerifyGoogleMutationOptions(options), queryClient);
};
export type appleWebhookResponse200 = {
  data: IapVerifyResponse;
  status: 200;
};

export type appleWebhookResponse400 = {
  data: ResultObject;
  status: 400;
};

export type appleWebhookResponse405 = {
  data: ResultObject;
  status: 405;
};

export type appleWebhookResponse500 = {
  data: ResultObject;
  status: 500;
};

export type appleWebhookResponseSuccess = appleWebhookResponse200 & {
  headers: Headers;
};
export type appleWebhookResponseError = (
  | appleWebhookResponse400
  | appleWebhookResponse405
  | appleWebhookResponse500
) & {
  headers: Headers;
};

export type appleWebhookResponse =
  | appleWebhookResponseSuccess
  | appleWebhookResponseError;

export const getAppleWebhookUrl = (key: string) => {
  return `/api/userWallet/iap/apple/webhook/${key}`;
};

export const appleWebhook = async (
  key: string,
  appleIapWebhookRequest: AppleIapWebhookRequest,
  options?: RequestInit,
): Promise<appleWebhookResponse> => {
  return appAxiosInstance<appleWebhookResponse>(getAppleWebhookUrl(key), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(appleIapWebhookRequest),
  });
};

export const getAppleWebhookMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof appleWebhook>>,
    TError,
    { key: string; data: AppleIapWebhookRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof appleWebhook>>,
  TError,
  { key: string; data: AppleIapWebhookRequest },
  TContext
> => {
  const mutationKey = ['appleWebhook'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof appleWebhook>>,
    { key: string; data: AppleIapWebhookRequest }
  > = (props) => {
    const { key, data } = props ?? {};

    return appleWebhook(key, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AppleWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof appleWebhook>>
>;
export type AppleWebhookMutationBody = AppleIapWebhookRequest;
export type AppleWebhookMutationError = ResultObject;

export const useAppleWebhook = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof appleWebhook>>,
      TError,
      { key: string; data: AppleIapWebhookRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof appleWebhook>>,
  TError,
  { key: string; data: AppleIapWebhookRequest },
  TContext
> => {
  return useMutation(getAppleWebhookMutationOptions(options), queryClient);
};
export type verifyAppleResponse200 = {
  data: IapVerifyResponse;
  status: 200;
};

export type verifyAppleResponse400 = {
  data: ResultObject;
  status: 400;
};

export type verifyAppleResponse405 = {
  data: ResultObject;
  status: 405;
};

export type verifyAppleResponse500 = {
  data: ResultObject;
  status: 500;
};

export type verifyAppleResponseSuccess = verifyAppleResponse200 & {
  headers: Headers;
};
export type verifyAppleResponseError = (
  | verifyAppleResponse400
  | verifyAppleResponse405
  | verifyAppleResponse500
) & {
  headers: Headers;
};

export type verifyAppleResponse =
  | verifyAppleResponseSuccess
  | verifyAppleResponseError;

export const getVerifyAppleUrl = () => {
  return `/api/userWallet/iap/apple/verify`;
};

export const verifyApple = async (
  appleIapVerifyRequest: AppleIapVerifyRequest,
  options?: RequestInit,
): Promise<verifyAppleResponse> => {
  return appAxiosInstance<verifyAppleResponse>(getVerifyAppleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(appleIapVerifyRequest),
  });
};

export const getVerifyAppleMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyApple>>,
    TError,
    { data: AppleIapVerifyRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof verifyApple>>,
  TError,
  { data: AppleIapVerifyRequest },
  TContext
> => {
  const mutationKey = ['verifyApple'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof verifyApple>>,
    { data: AppleIapVerifyRequest }
  > = (props) => {
    const { data } = props ?? {};

    return verifyApple(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type VerifyAppleMutationResult = NonNullable<
  Awaited<ReturnType<typeof verifyApple>>
>;
export type VerifyAppleMutationBody = AppleIapVerifyRequest;
export type VerifyAppleMutationError = ResultObject;

export const useVerifyApple = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof verifyApple>>,
      TError,
      { data: AppleIapVerifyRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof verifyApple>>,
  TError,
  { data: AppleIapVerifyRequest },
  TContext
> => {
  return useMutation(getVerifyAppleMutationOptions(options), queryClient);
};
export type queryOrderResponse200 = {
  data: IapVerifyResponse;
  status: 200;
};

export type queryOrderResponse400 = {
  data: ResultObject;
  status: 400;
};

export type queryOrderResponse405 = {
  data: ResultObject;
  status: 405;
};

export type queryOrderResponse500 = {
  data: ResultObject;
  status: 500;
};

export type queryOrderResponseSuccess = queryOrderResponse200 & {
  headers: Headers;
};
export type queryOrderResponseError = (
  | queryOrderResponse400
  | queryOrderResponse405
  | queryOrderResponse500
) & {
  headers: Headers;
};

export type queryOrderResponse =
  | queryOrderResponseSuccess
  | queryOrderResponseError;

export const getQueryOrderUrl = (orderId: string) => {
  return `/api/userWallet/iap/orders/${orderId}`;
};

/**
 * @summary Query local IAP order status
 */
export const queryOrder = async (
  orderId: string,
  options?: RequestInit,
): Promise<queryOrderResponse> => {
  return appAxiosInstance<queryOrderResponse>(getQueryOrderUrl(orderId), {
    ...options,
    method: 'GET',
  });
};

export const getQueryOrderQueryKey = (orderId: string) => {
  return [`/api/userWallet/iap/orders/${orderId}`] as const;
};

export const getQueryOrderQueryOptions = <
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryOrder>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQueryOrderQueryKey(orderId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof queryOrder>>> = ({
    signal,
  }) => queryOrder(orderId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: orderId !== null && orderId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryOrder>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryOrderQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryOrder>>
>;
export type QueryOrderQueryError = ResultObject;

export function useQueryOrder<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryOrder>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryOrder>>,
          TError,
          Awaited<ReturnType<typeof queryOrder>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryOrder<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryOrder>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryOrder>>,
          TError,
          Awaited<ReturnType<typeof queryOrder>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryOrder<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryOrder>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query local IAP order status
 */

export function useQueryOrder<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryOrder>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryOrderQueryOptions(orderId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getQueryOrderSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryOrder>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQueryOrderQueryKey(orderId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof queryOrder>>> = ({
    signal,
  }) => queryOrder(orderId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof queryOrder>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryOrderSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryOrder>>
>;
export type QueryOrderSuspenseQueryError = ResultObject;

export function useQueryOrderSuspense<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryOrder>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryOrderSuspense<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryOrder>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryOrderSuspense<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryOrder>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query local IAP order status
 */

export function useQueryOrderSuspense<
  TData = Awaited<ReturnType<typeof queryOrder>>,
  TError = ResultObject,
>(
  orderId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryOrder>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryOrderSuspenseQueryOptions(orderId, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
