/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 活动信息
 */
export interface ActivityInfoResponse {
  /** 活动 ID */
  activityId?: number;
  /** 活动开始时间（epoch ms） */
  activityStartAt?: number;
  /** 活动结束时间（epoch ms） */
  activityEndAt?: number;
  /** 最低奖励额度（USDC，排行榜档位；无配置时为 null） */
  minRewardAmount?: number;
  /** 最高奖励额度（USDC，排行榜档位；无配置时为 null） */
  maxRewardAmount?: number;
}
