/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 演员金库排行单项
 */
export interface ActorVaultRanking {
  /** 排名顺序，从 1 开始 */
  rank?: number;
  /** 演员合集名称 */
  actorName?: string;
  /** 演员编号（格式：#XXXX） */
  number?: string;
  /** 演员合集 ID（大整数） */
  actorId?: number;
  /** 该演员的金库总资金（USDC，精度 6 位小数，显示 4 位） */
  vault?: number;
}
