/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * Actor NFT 合成升级订单响应（含合约调用签名）
 */
export interface ActorNftUpgradeOrderResponse {
  /** Ed25519 签名，Base64 编码 */
  sig?: string;
  /** 签名过期时间，秒级时间戳 */
  expiresAt?: string;
  /** 签名前明文（canonicalPayload，| 拼接，sig 对其签名） */
  payload?: string;
}
