/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 演员合集金库沉淀金额
 */
export interface ActorNftVaultDepositResponse {
  /** 演员合集ID */
  actorCollectionId?: string;
  /** 金库累计沉淀金额（USDC） */
  vaultAmount?: string;
}
