/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItem } from './applicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItem';

export type ApplicationContextClassLoaderParentUnnamedModuleClassLoader = {
  name?: string;
  registeredAsParallelCapable?: boolean;
  definedPackages?: ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackagesItem[];
  defaultAssertionStatus?: boolean;
};
