/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ApplicationContext as __ApplicationContext } from './applicationContext';
import type { ApplicationContextClassLoader } from './applicationContextClassLoader';
import type { AutowireCapableBeanFactory } from './autowireCapableBeanFactory';
import type { BeanFactory } from './beanFactory';
import type { Environment } from './environment';

export interface ApplicationContext {
  parent?: __ApplicationContext;
  id?: string;
  displayName?: string;
  applicationName?: string;
  startupDate?: number;
  autowireCapableBeanFactory?: AutowireCapableBeanFactory;
  environment?: Environment;
  beanDefinitionCount?: number;
  beanDefinitionNames?: string[];
  parentBeanFactory?: BeanFactory;
  classLoader?: ApplicationContextClassLoader;
}
