/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ApplicationContextClassLoaderUnnamedModuleAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleAnnotationsItem';
import type { ApplicationContextClassLoaderUnnamedModuleClassLoader } from './applicationContextClassLoaderUnnamedModuleClassLoader';
import type { ApplicationContextClassLoaderUnnamedModuleDeclaredAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleDeclaredAnnotationsItem';
import type { ApplicationContextClassLoaderUnnamedModuleDescriptor } from './applicationContextClassLoaderUnnamedModuleDescriptor';
import type { ApplicationContextClassLoaderUnnamedModuleLayer } from './applicationContextClassLoaderUnnamedModuleLayer';

export type ApplicationContextClassLoaderUnnamedModule = {
  name?: string;
  classLoader?: ApplicationContextClassLoaderUnnamedModuleClassLoader;
  descriptor?: ApplicationContextClassLoaderUnnamedModuleDescriptor;
  named?: boolean;
  annotations?: ApplicationContextClassLoaderUnnamedModuleAnnotationsItem[];
  declaredAnnotations?: ApplicationContextClassLoaderUnnamedModuleDeclaredAnnotationsItem[];
  packages?: string[];
  layer?: ApplicationContextClassLoaderUnnamedModuleLayer;
};
