/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

export type ApplicationContextClassLoaderUnnamedModuleDeclaredAnnotationsItem =
  { [key: string]: unknown };
