/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * Apple Server Notification V2 请求
 */
export interface AppleIapWebhookRequest {
  /** Apple Server Notification V2 signedPayload */
  signedPayload: string;
}
