/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ApplicationContextClassLoaderParentDefinedPackagesItem } from './applicationContextClassLoaderParentDefinedPackagesItem';
import type { ApplicationContextClassLoaderParentUnnamedModule } from './applicationContextClassLoaderParentUnnamedModule';

export type ApplicationContextClassLoaderParent = {
  name?: string;
  registeredAsParallelCapable?: boolean;
  unnamedModule?: ApplicationContextClassLoaderParentUnnamedModule;
  definedPackages?: ApplicationContextClassLoaderParentDefinedPackagesItem[];
  defaultAssertionStatus?: boolean;
};
