/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * Apple IAP 客户端验单请求
 */
export interface AppleIapVerifyRequest {
  /** 后端创建的全局唯一订单号 */
  orderId: string;
  /** Apple StoreKit 2 signedTransactionInfo */
  signedTransactionInfo: string;
}
