/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem';
import type { ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem } from './applicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem';

export type ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItem =
  {
    name?: string;
    annotations?: ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemAnnotationsItem[];
    declaredAnnotations?: ApplicationContextClassLoaderUnnamedModuleClassLoaderDefinedPackagesItemDeclaredAnnotationsItem[];
    sealed?: boolean;
    specificationTitle?: string;
    specificationVersion?: string;
    specificationVendor?: string;
    implementationTitle?: string;
    implementationVersion?: string;
    implementationVendor?: string;
  };
