/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ApplicationContextClassLoaderParentUnnamedModuleAnnotationsItem } from './applicationContextClassLoaderParentUnnamedModuleAnnotationsItem';
import type { ApplicationContextClassLoaderParentUnnamedModuleClassLoader } from './applicationContextClassLoaderParentUnnamedModuleClassLoader';
import type { ApplicationContextClassLoaderParentUnnamedModuleDeclaredAnnotationsItem } from './applicationContextClassLoaderParentUnnamedModuleDeclaredAnnotationsItem';
import type { ApplicationContextClassLoaderParentUnnamedModuleDescriptor } from './applicationContextClassLoaderParentUnnamedModuleDescriptor';
import type { ApplicationContextClassLoaderParentUnnamedModuleLayer } from './applicationContextClassLoaderParentUnnamedModuleLayer';

export type ApplicationContextClassLoaderParentUnnamedModule = {
  name?: string;
  classLoader?: ApplicationContextClassLoaderParentUnnamedModuleClassLoader;
  descriptor?: ApplicationContextClassLoaderParentUnnamedModuleDescriptor;
  named?: boolean;
  annotations?: ApplicationContextClassLoaderParentUnnamedModuleAnnotationsItem[];
  declaredAnnotations?: ApplicationContextClassLoaderParentUnnamedModuleDeclaredAnnotationsItem[];
  packages?: string[];
  layer?: ApplicationContextClassLoaderParentUnnamedModuleLayer;
};
