/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 任务类型
 */
export type CompleteTaskResponseType =
  (typeof CompleteTaskResponseType)[keyof typeof CompleteTaskResponseType];

export const CompleteTaskResponseType = {
  follow_x: 'follow_x',
  retweet_x: 'retweet_x',
  like_x: 'like_x',
} as const;
