/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { DramaNftPositionItemResponse } from './dramaNftPositionItemResponse';

/**
 * 短剧 NFT 持仓分页结果（首页带持有总数 total）
 */
export interface DramaNftPositionPageResponse {
  /** 持有短剧 NFT 总数（仅首页返回） */
  total?: string;
  /** 下一页游标，-1 表示末页 */
  mark?: string;
  /** 每页数量 */
  pageSize?: string;
  /** 是否还有更多数据 */
  hasMore?: boolean;
  /** 短剧 NFT 持仓列表 */
  list?: DramaNftPositionItemResponse[];
}
