/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 短剧 NFT 持仓项
 */
export interface DramaNftPositionItemResponse {
  /** 短剧 ID */
  dramaId?: string;
  /** NFT 链上合约/铸造地址 */
  nftContractAddress?: string;
  /** 短剧名称 */
  dramaName?: string;
  /** 封面 URL */
  coverUrl?: string;
  /** 总集数 */
  episodeCount?: string;
  /** 短剧简介 */
  description?: string;
  /** 持仓状态：1-正常 2-已销毁 */
  status?: string;
  /** 铸造入账时间，毫秒时间戳 */
  createdAt?: string;
}
