/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 邮箱+密码登录请求（内部/测试用）
 */
export interface EmailLoginRequest {
  /** 邮箱 */
  email: string;
  /** 登录密码 */
  password: string;
}
