/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 邮箱+密码注册请求（内部/测试用）
 */
export interface EmailRegisterRequest {
  /** 邮箱，全局唯一 */
  email: string;
  /**
   * 登录密码，6-32 位
   * @minLength 6
   * @maxLength 32
   */
  password: string;
  /** 邀请码，仅注册时绑定邀请关系 */
  inviteCode?: string;
}
