/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 邮箱+密码注册响应
 */
export interface EmailRegisterResponse {
  /** 用户ID */
  userId?: number;
  /** 用户邀请码 */
  inviteCode?: string;
}
