/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 活动定稿请求
 */
export interface FinalizeActivityRequest {
  /**
   * 操作人（最长 100 字符）
   * @minLength 0
   * @maxLength 100
   */
  finalizedBy?: string;
}
