/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

export type FollowersParams = {
  /**
   * 下一页游标，首次传 0
   */
  mark?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
};
