/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { FollowRelationResponseStatus } from './followRelationResponseStatus';

/**
 * 关注关系状态
 */
export interface FollowRelationResponse {
  /** 当前登录用户对该用户的关系状态 */
  status?: FollowRelationResponseStatus;
}
