/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { IapOrderResponsePaymentChannel } from './iapOrderResponsePaymentChannel';

export interface IapOrderResponse {
  orderId?: string;
  paymentChannel?: IapOrderResponsePaymentChannel;
  productId?: string;
  purchaseAmount?: number;
  currency?: string;
  tokenAmount?: number;
  providerAccountId?: string;
  status?: number;
  statusName?: string;
  createdAt?: number;
}
