/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { IapVerifyResponsePaymentChannel } from './iapVerifyResponsePaymentChannel';

export interface IapVerifyResponse {
  orderId?: string;
  paymentChannel?: IapVerifyResponsePaymentChannel;
  purchaseAmount?: number;
  tokenAmount?: number;
  currency?: string;
  createdAt?: number;
  status?: number;
  statusName?: string;
  providerTransactionId?: string;
  operatorOrderId?: string;
  operatorStatus?: string;
}
