/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 内部扣款订单结果响应
 */
export interface InternalDebitResultResponse {
  /** 处理状态 */
  status?: string;
  /** 用户ID */
  userId?: string;
  /** 资产编码 */
  assetCode?: string;
  /** 金额 */
  amount?: string;
  /** 业务单号 */
  orderNo?: string;
  /** 资产流水ID */
  ledgerId?: string;
}
