/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 用户资产流水
 */
export interface LedgerItemResponse {
  /** 资产编码 */
  assetCode?: string;
  /** 业务类型；STORY：1001-派遣收益入账、1002-邀请收益入账、1003-提取成功扣减、1004-人工补发、1005-人工扣减；USDC：1101-演员签约分成入账、1102-提取成功扣减、1103-人工补发、1104-人工扣减 */
  bizType?: string;
  /** 变动金额 */
  changeAmount?: string;
  /** 变更后可用余额 */
  availableAfter?: string;
  /** 业务单号 */
  orderNo?: string;
  /** 备注 */
  remark?: string;
  /** 创建时间，毫秒时间戳 */
  createdAt?: string;
}
