/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { UserProfileResponse } from './userProfileResponse';

/**
 * 登录响应
 */
export interface LoginResponse {
  /** 平台登录态 token */
  token?: string;
  userProfile?: UserProfileResponse;
}
