/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 登录 / 首次注册请求
 */
export interface LoginRequest {
  /** 前端从 Privy 获取的登录凭证 */
  privyToken: string;
  /** 邀请码，仅首次注册时生效 */
  inviteCode?: string;
}
