/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ManualScrapeItemResponse } from './manualScrapeItemResponse';

/**
 * 手动触发爬虫响应
 */
export interface ManualScrapeResponse {
  /** 每条 attempt 的抓取结果 */
  results?: ManualScrapeItemResponse[];
  /** 本次抓取按 rules 聚合后的总积分（仅成功抓取的 attempt） */
  totalPoints?: number;
  /** 是否成功发送了 FINAL_POINTS_SNAPSHOT Kafka 事件 */
  kafkaEmitted?: boolean;
  /** Kafka 事件的幂等键（与活动结算同款：final:{activityId}:{userId}） */
  idempotencyKey?: string;
}
