/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { NotificationItemResponseData } from './notificationItemResponseData';

/**
 * 站内通知列表项
 */
export interface NotificationItemResponse {
  /** 通知 ID，字符串形式避免前端整数精度丢失 */
  id?: string;
  /** 所属 Tab：1-收益 2-互动 */
  tab?: number;
  /** 通知类型（字符串枚举）LIKE-点赞 COMMENT-评论 FAVORITE-收藏 FOLLOW-关注 STAMINA_LOW-体力不足 SHOW_REWARD-演出奖励 IP_SIGN-签约角色 */
  eventType?: string;
  /** 操作人用户 ID；系统类通知为空 */
  operateUserId?: string;
  /** 操作人最新昵称，按 operateUserId 读时联查 */
  operateNickname?: string;
  /** 操作人最新头像 URL，互动类通知用作卡片头像 */
  operateAvatarUrl?: string;
  /** 是否已读：1-已读 0-未读 */
  isRead?: number;
  /** 业务发生时间，毫秒时间戳字符串 */
  eventTime?: string;
  /**
   * 类型专属数据，字段随 eventType 变化，只有对应类型的字段才有值：
   * · IP_SIGN 签约分成：behaviorId(签约行为id)、objectId(角色IP id)、ipName(角色IP名)、ipAvatarUrl(角色IP形象)、amount(分成金额)、assetCode(固定USDC)
   * · SHOW_REWARD 演出收益：behaviorId(结算行为id)、objectId(收益明细id)、amount(收益金额)、assetCode(固定STORY)、periodStart(结算周期起,ms)、periodEnd(结算周期止,ms)
   * · STAMINA_LOW 体力不足：behaviorId(体力行为id)、objectId(角色IP id)、ipName(角色IP名)、ipAvatarUrl(角色IP形象)、stamina(当前体力)
   * · LIKE/FAVORITE 点赞/收藏：behaviorId(行为id)、objectId(目标id)、targetType(video-单集/drama-短剧)、targetName(目标名称)、coverUrl(封面)
   * · COMMENT 评论：behaviorId(评论行为id)、objectId(目标id)、targetType(video-单集/drama-短剧)、content(评论正文快照)、targetName(目标名称)、coverUrl(封面)
   * · FOLLOW 关注：behaviorId(关注关系id)、objectId(被关注用户id)、followStatus(关注状态 MUTUAL-互关，FOLLOWING-已关注对方，"
   *                                                                                + "FOLLOW_BACK-对方关注我，NONE-双方未关注)
   */
  data?: NotificationItemResponseData;
}
