/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { NotificationBackdoorRequestEventType } from './notificationBackdoorRequestEventType';

/**
 * 站内通知测试请求
 */
export interface NotificationBackdoorRequest {
  /** 通知接收用户 ID；Kafka Message Key 和 WS 私有频道均由该值决定 */
  targetUserId: number;
  /** 通知类型；支持 NotificationTypeEnum 的全部 7 种枚举值 */
  eventType: NotificationBackdoorRequestEventType;
}
