/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 平台账户余额响应
 */
export interface PlatformBalanceResponse {
  /** 平台账户ID */
  platformAccountId?: string;
  /** 资产编码 */
  assetCode?: string;
  /** 可用余额 */
  availableBalance?: string;
  /** 冻结余额 */
  frozenBalance?: string;
}
