/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

export type PointsLedgerParams = {
  /**
   * 活动 ID
   */
  activityId: number;
  /**
   * 游标，首屏传 0
   */
  mark?: number;
  /**
   * 每页条数，默认 20
   */
  pageSize?: number;
};
