/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 驳回分享 attempt 请求
 */
export interface RejectShareAttemptRequest {
  /**
   * 拒绝理由（最长 500 字符）
   * @minLength 0
   * @maxLength 500
   */
  reason?: string;
}
