/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ResultMapLongStringData } from './resultMapLongStringData';

/**
 * 统一响应结构
 */
export interface ResultMapLongString {
  /** 响应消息 */
  msg?: string;
  /** 响应码 */
  code?: number;
  /** 响应数据 */
  data?: ResultMapLongStringData;
}
