/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

export type SearchUsersParams = {
  /**
   * 搜索关键字
   */
  keyword: string;
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页数量
   */
  pageSize?: number;
};
