/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { JspConfigDescriptor } from './jspConfigDescriptor';
import type { ServletContextAttributeNames } from './servletContextAttributeNames';
import type { ServletContextClassLoader } from './servletContextClassLoader';
import type { ServletContextDefaultSessionTrackingModesItem } from './servletContextDefaultSessionTrackingModesItem';
import type { ServletContextEffectiveSessionTrackingModesItem } from './servletContextEffectiveSessionTrackingModesItem';
import type { ServletContextFilterRegistrations } from './servletContextFilterRegistrations';
import type { ServletContextInitParameterNames } from './servletContextInitParameterNames';
import type { ServletContextServletRegistrations } from './servletContextServletRegistrations';
import type { ServletContextSessionTrackingModesItem } from './servletContextSessionTrackingModesItem';
import type { SessionCookieConfig } from './sessionCookieConfig';

export interface ServletContext {
  classLoader?: ServletContextClassLoader;
  majorVersion?: number;
  minorVersion?: number;
  attributeNames?: ServletContextAttributeNames;
  contextPath?: string;
  initParameterNames?: ServletContextInitParameterNames;
  sessionTimeout?: number;
  effectiveMajorVersion?: number;
  effectiveMinorVersion?: number;
  serverInfo?: string;
  servletContextName?: string;
  servletRegistrations?: ServletContextServletRegistrations;
  filterRegistrations?: ServletContextFilterRegistrations;
  sessionCookieConfig?: SessionCookieConfig;
  sessionTrackingModes?: ServletContextSessionTrackingModesItem[];
  defaultSessionTrackingModes?: ServletContextDefaultSessionTrackingModesItem[];
  effectiveSessionTrackingModes?: ServletContextEffectiveSessionTrackingModesItem[];
  jspConfigDescriptor?: JspConfigDescriptor;
  virtualServerName?: string;
  requestCharacterEncoding?: string;
  responseCharacterEncoding?: string;
}
