/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { ShareAttemptResponsePlatform } from './shareAttemptResponsePlatform';
import type { ShareAttemptResponseStatus } from './shareAttemptResponseStatus';

/**
 * 分享 attempt 状态
 */
export interface ShareAttemptResponse {
  /** attempt ID */
  attemptId?: number;
  /** 分享平台 */
  platform?: ShareAttemptResponsePlatform;
  /** SF code（短码） */
  code?: string;
  /** 审核状态 */
  status?: ShareAttemptResponseStatus;
  /** 分享 URL */
  shareUrl?: string;
  /** 提交时间（epoch ms） */
  submittedAt?: number;
  /** 通过时间（epoch ms） */
  approvedAt?: number;
  /** 驳回时间（epoch ms） */
  rejectedAt?: number;
  /** 拒绝理由 */
  rejectionReason?: string;
}
