/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 社交账号绑定状态
 */
export interface SocialBindStatusResponse {
  /** 是否已绑定 */
  bound?: boolean;
  /** 平台用户名 */
  platformUsername?: string;
  /** 平台头像URL */
  platformAvatarUrl?: string;
  /** 绑定时间 */
  boundAt?: string;
}
