/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { SubmitShareAttemptRequestPlatform } from './submitShareAttemptRequestPlatform';

/**
 * 提交分享 attempt 请求
 */
export interface SubmitShareAttemptRequest {
  /** 分享平台（大小写不敏感） */
  platform: SubmitShareAttemptRequestPlatform;
  /** 分享 URL（必填，需符合对应平台格式） */
  shareUrl: string;
}
