/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { PreSignedPutUrlResult } from './preSignedPutUrlResult';

/**
 * 故事提交响应
 */
export interface SubmitStoryResponse {
  /** 故事ID */
  storyId?: number;
  urlResult?: PreSignedPutUrlResult;
}
