/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 修改昵称和简介请求
 */
export interface UpdateNicknameRequest {
  /**
   * 用户昵称，最长 64 字符
   * @maxLength 64
   */
  nickname: string;
  /**
   * 用户简介，最长 200 字符
   * @maxLength 200
   */
  profile?: string;
}
