/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

export interface UpdateUserTrustRequest {
  /** 用户ID */
  userId: string;
  /**
   * 用户信任度，范围 [0.00, 1.00]
   * @minimum 0
   * @maximum 1
   */
  trust: number;
}
