/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { UpdateUserDeletedRequestIsDeleted } from './updateUserDeletedRequestIsDeleted';

/**
 * 修改当前登录用户删除标志位请求
 */
export interface UpdateUserDeletedRequest {
  /**
   * 删除标志位：0-未删除，1-已删除
   * @minimum 0
   * @maximum 1
   */
  isDeleted: UpdateUserDeletedRequestIsDeleted;
}
