/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 删除标志位：0-未删除，1-已删除
 * @minimum 0
 * @maximum 1
 */
export type UpdateUserDeletedRequestIsDeleted =
  (typeof UpdateUserDeletedRequestIsDeleted)[keyof typeof UpdateUserDeletedRequestIsDeleted];

export const UpdateUserDeletedRequestIsDeleted = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
