/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * USDC 收益项（演员铸造分成）
 */
export interface UsdcIncomeItemResponse {
  /** 分账记录ID（游标用） */
  id?: string;
  /** 收益时间，毫秒时间戳 */
  createdAt?: string;
  /** 收益类型 code，前端映射文案 */
  type?: string;
  /** 来源演员合集ID（drama_actor_collection.id，展示编号） */
  actorCollectionId?: string;
  /** 该笔铸造分账对应的演员 NFT tokenId */
  tokenId?: string;
  /** 来源演员名称 */
  actorName?: string;
  /** 收益金额（USDC） */
  amount?: string;
  /** 分账状态：0-待入账 1-已确认 2-失败 */
  status?: string;
}
