/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */
import type { CursorPageResponseFollowListItemResponse } from './cursorPageResponseFollowListItemResponse';

/**
 * 用户连接列表（粉丝 + 互关）
 */
export interface UserConnectionsResponse {
  /** 目标用户ID */
  targetUserId?: string;
  followers?: CursorPageResponseFollowListItemResponse;
  mutuals?: CursorPageResponseFollowListItemResponse;
}
