/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 金库统计
 */
export interface VaultStatsResponse {
  /** 金库总资金（USDC，精度 6 位小数，显示 4 位） */
  totalVault?: number;
  /** 金库覆盖的演员 IP 数量 */
  actorCount?: number;
}
