/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

/**
 * 发起提取请求
 */
export interface WithdrawRequest {
  /** 提取资产编码：STORY、USDC */
  assetCode: string;
  /** 提取目标钱包地址 */
  toAddress: string;
}
