/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ResultObject,
  UsdcIncomePageResponse,
  UsdcIncomeParams,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type usdcIncomeResponse200 = {
  data: ResultObject;
  status: 200;
};

export type usdcIncomeResponse400 = {
  data: ResultObject;
  status: 400;
};

export type usdcIncomeResponse401 = {
  data: UsdcIncomePageResponse;
  status: 401;
};

export type usdcIncomeResponse405 = {
  data: ResultObject;
  status: 405;
};

export type usdcIncomeResponse500 = {
  data: ResultObject;
  status: 500;
};

export type usdcIncomeResponseSuccess = usdcIncomeResponse200 & {
  headers: Headers;
};
export type usdcIncomeResponseError = (
  | usdcIncomeResponse400
  | usdcIncomeResponse401
  | usdcIncomeResponse405
  | usdcIncomeResponse500
) & {
  headers: Headers;
};

export type usdcIncomeResponse =
  | usdcIncomeResponseSuccess
  | usdcIncomeResponseError;

export const getUsdcIncomeUrl = (params?: UsdcIncomeParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/userWallet/income/usdc?${stringifiedParams}`
    : `/api/userWallet/income/usdc`;
};

/**
 * 分页查询当前登录用户的 USDC 收益（演员铸造分成-发行人份额，不按状态过滤，来源演员按 actorCollectionId 联表 drama_actor_collection 取名），首页（mark=0）在 total 返回累计 USDC 收益。可领取 USDC 取资产列表的 USDC 可用余额。
 * @summary 查询个人 USDC 收益列表
 */
export const usdcIncome = async (
  params?: UsdcIncomeParams,
  options?: RequestInit,
): Promise<usdcIncomeResponse> => {
  return appAxiosInstance<usdcIncomeResponse>(getUsdcIncomeUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getUsdcIncomeQueryKey = (params?: UsdcIncomeParams) => {
  return [`/api/userWallet/income/usdc`, ...(params ? [params] : [])] as const;
};

export const getUsdcIncomeQueryOptions = <
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usdcIncome>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsdcIncomeQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usdcIncome>>> = ({
    signal,
  }) => usdcIncome(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usdcIncome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsdcIncomeQueryResult = NonNullable<
  Awaited<ReturnType<typeof usdcIncome>>
>;
export type UsdcIncomeQueryError = ResultObject | UsdcIncomePageResponse;

export function useUsdcIncome<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params: undefined | UsdcIncomeParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usdcIncome>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usdcIncome>>,
          TError,
          Awaited<ReturnType<typeof usdcIncome>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsdcIncome<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usdcIncome>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usdcIncome>>,
          TError,
          Awaited<ReturnType<typeof usdcIncome>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsdcIncome<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usdcIncome>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询个人 USDC 收益列表
 */

export function useUsdcIncome<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usdcIncome>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsdcIncomeQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getUsdcIncomeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof usdcIncome>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsdcIncomeQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usdcIncome>>> = ({
    signal,
  }) => usdcIncome(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof usdcIncome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsdcIncomeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof usdcIncome>>
>;
export type UsdcIncomeSuspenseQueryError =
  | ResultObject
  | UsdcIncomePageResponse;

export function useUsdcIncomeSuspense<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params: undefined | UsdcIncomeParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof usdcIncome>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsdcIncomeSuspense<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof usdcIncome>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsdcIncomeSuspense<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof usdcIncome>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询个人 USDC 收益列表
 */

export function useUsdcIncomeSuspense<
  TData = Awaited<ReturnType<typeof usdcIncome>>,
  TError = ResultObject | UsdcIncomePageResponse,
>(
  params?: UsdcIncomeParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof usdcIncome>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsdcIncomeSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
