/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  CancelSession200,
  CreateUploadPresignRequest,
  CreateUploadSessionResponse,
  ResultBoolean,
  ResultObject,
  UploadPresignResponse,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createSessionResponse200 = {
  data: CreateUploadSessionResponse;
  status: 200;
};

export type createSessionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type createSessionResponseSuccess = createSessionResponse200 & {
  headers: Headers;
};
export type createSessionResponseError = createSessionResponse400 & {
  headers: Headers;
};

export type createSessionResponse =
  | createSessionResponseSuccess
  | createSessionResponseError;

export const getCreateSessionUrl = () => {
  return `/api/mini-drama/creator/uploads/sessions`;
};

/**
 * @summary [鉴权]生成全局上传会话
 */
export const createSession = async (
  options?: RequestInit,
): Promise<createSessionResponse> => {
  return appAxiosInstance<createSessionResponse>(getCreateSessionUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getCreateSessionMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSession>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSession>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['createSession'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSession>>,
    void
  > = () => {
    return createSession(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSession>>
>;

export type CreateSessionMutationError = ResultObject;

/**
 * @summary [鉴权]生成全局上传会话
 */
export const useCreateSession = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSession>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSession>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getCreateSessionMutationOptions(options), queryClient);
};
export type createPresignResponse200 = {
  data: UploadPresignResponse;
  status: 200;
};

export type createPresignResponse400 = {
  data: ResultObject;
  status: 400;
};

export type createPresignResponseSuccess = createPresignResponse200 & {
  headers: Headers;
};
export type createPresignResponseError = createPresignResponse400 & {
  headers: Headers;
};

export type createPresignResponse =
  | createPresignResponseSuccess
  | createPresignResponseError;

export const getCreatePresignUrl = () => {
  return `/api/mini-drama/creator/uploads/presign`;
};

/**
 * 上传组件
 * @summary [鉴权]生成S3上传预签名URL
 */
export const createPresign = async (
  createUploadPresignRequest: CreateUploadPresignRequest,
  options?: RequestInit,
): Promise<createPresignResponse> => {
  return appAxiosInstance<createPresignResponse>(getCreatePresignUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUploadPresignRequest),
  });
};

export const getCreatePresignMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPresign>>,
    TError,
    { data: CreateUploadPresignRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPresign>>,
  TError,
  { data: CreateUploadPresignRequest },
  TContext
> => {
  const mutationKey = ['createPresign'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPresign>>,
    { data: CreateUploadPresignRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createPresign(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePresignMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPresign>>
>;
export type CreatePresignMutationBody = CreateUploadPresignRequest;
export type CreatePresignMutationError = ResultObject;

/**
 * @summary [鉴权]生成S3上传预签名URL
 */
export const useCreatePresign = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPresign>>,
      TError,
      { data: CreateUploadPresignRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPresign>>,
  TError,
  { data: CreateUploadPresignRequest },
  TContext
> => {
  return useMutation(getCreatePresignMutationOptions(options), queryClient);
};
export type isExpiredResponse200 = {
  data: ResultBoolean;
  status: 200;
};

export type isExpiredResponse400 = {
  data: ResultObject;
  status: 400;
};

export type isExpiredResponseSuccess = isExpiredResponse200 & {
  headers: Headers;
};
export type isExpiredResponseError = isExpiredResponse400 & {
  headers: Headers;
};

export type isExpiredResponse =
  | isExpiredResponseSuccess
  | isExpiredResponseError;

export const getIsExpiredUrl = (uploadSessionId: number) => {
  return `/api/mini-drama/creator/uploads/sessions/${uploadSessionId}/expired`;
};

/**
 * @summary [鉴权]判断全局上传会话是否过期
 */
export const isExpired = async (
  uploadSessionId: number,
  options?: RequestInit,
): Promise<isExpiredResponse> => {
  return appAxiosInstance<isExpiredResponse>(getIsExpiredUrl(uploadSessionId), {
    ...options,
    method: 'GET',
  });
};

export const getIsExpiredQueryKey = (uploadSessionId: number) => {
  return [
    `/api/mini-drama/creator/uploads/sessions/${uploadSessionId}/expired`,
  ] as const;
};

export const getIsExpiredQueryOptions = <
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isExpired>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getIsExpiredQueryKey(uploadSessionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof isExpired>>> = ({
    signal,
  }) => isExpired(uploadSessionId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: uploadSessionId !== null && uploadSessionId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof isExpired>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type IsExpiredQueryResult = NonNullable<
  Awaited<ReturnType<typeof isExpired>>
>;
export type IsExpiredQueryError = ResultObject;

export function useIsExpired<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isExpired>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof isExpired>>,
          TError,
          Awaited<ReturnType<typeof isExpired>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useIsExpired<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isExpired>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof isExpired>>,
          TError,
          Awaited<ReturnType<typeof isExpired>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useIsExpired<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isExpired>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]判断全局上传会话是否过期
 */

export function useIsExpired<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isExpired>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getIsExpiredQueryOptions(uploadSessionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getIsExpiredSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof isExpired>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getIsExpiredQueryKey(uploadSessionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof isExpired>>> = ({
    signal,
  }) => isExpired(uploadSessionId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof isExpired>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type IsExpiredSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof isExpired>>
>;
export type IsExpiredSuspenseQueryError = ResultObject;

export function useIsExpiredSuspense<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof isExpired>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useIsExpiredSuspense<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof isExpired>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useIsExpiredSuspense<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof isExpired>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]判断全局上传会话是否过期
 */

export function useIsExpiredSuspense<
  TData = Awaited<ReturnType<typeof isExpired>>,
  TError = ResultObject,
>(
  uploadSessionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof isExpired>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getIsExpiredSuspenseQueryOptions(
    uploadSessionId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type cancelSessionResponse200 = {
  data: CancelSession200;
  status: 200;
};

export type cancelSessionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type cancelSessionResponseSuccess = cancelSessionResponse200 & {
  headers: Headers;
};
export type cancelSessionResponseError = cancelSessionResponse400 & {
  headers: Headers;
};

export type cancelSessionResponse =
  | cancelSessionResponseSuccess
  | cancelSessionResponseError;

export const getCancelSessionUrl = (uploadSessionId: number) => {
  return `/api/mini-drama/creator/uploads/sessions/${uploadSessionId}`;
};

/**
 * @summary [鉴权]删除全局上传会话
 */
export const cancelSession = async (
  uploadSessionId: number,
  options?: RequestInit,
): Promise<cancelSessionResponse> => {
  return appAxiosInstance<cancelSessionResponse>(
    getCancelSessionUrl(uploadSessionId),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getCancelSessionMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelSession>>,
    TError,
    { uploadSessionId: number },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelSession>>,
  TError,
  { uploadSessionId: number },
  TContext
> => {
  const mutationKey = ['cancelSession'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelSession>>,
    { uploadSessionId: number }
  > = (props) => {
    const { uploadSessionId } = props ?? {};

    return cancelSession(uploadSessionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelSession>>
>;

export type CancelSessionMutationError = ResultObject;

/**
 * @summary [鉴权]删除全局上传会话
 */
export const useCancelSession = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelSession>>,
      TError,
      { uploadSessionId: number },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelSession>>,
  TError,
  { uploadSessionId: number },
  TContext
> => {
  return useMutation(getCancelSessionMutationOptions(options), queryClient);
};
