/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * 默认模块
 * 钱包服务 HTTP 接口 OpenAPI 文档。
 * 覆盖登录注册验签、邀请关系、用户资产、平台资产、充值、提现相关接口。
 *
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type { GetApiAdminV1ConfigsKeysKeys200 } from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiAdminV1ConfigsKeysKeysResponse200 = {
  data: GetApiAdminV1ConfigsKeysKeys200;
  status: 200;
};

export type getApiAdminV1ConfigsKeysKeysResponseSuccess =
  getApiAdminV1ConfigsKeysKeysResponse200 & {
    headers: Headers;
  };

export type getApiAdminV1ConfigsKeysKeysResponse =
  getApiAdminV1ConfigsKeysKeysResponseSuccess;

export const getGetApiAdminV1ConfigsKeysKeysUrl = (keys: string) => {
  return `/api/admin/v1/configs/keys/${keys}`;
};

/**
 * 根据单个 key 获取配置
 * @summary 根据多个 key 获取配置
 */
export const getApiAdminV1ConfigsKeysKeys = async (
  keys: string,
  options?: RequestInit,
): Promise<getApiAdminV1ConfigsKeysKeysResponse> => {
  return appAxiosInstance<getApiAdminV1ConfigsKeysKeysResponse>(
    getGetApiAdminV1ConfigsKeysKeysUrl(keys),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetApiAdminV1ConfigsKeysKeysQueryKey = (keys: string) => {
  return [`/api/admin/v1/configs/keys/${keys}`] as const;
};

export const getGetApiAdminV1ConfigsKeysKeysQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiAdminV1ConfigsKeysKeysQueryKey(keys);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>
  > = ({ signal }) =>
    getApiAdminV1ConfigsKeysKeys(keys, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: keys !== null && keys !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAdminV1ConfigsKeysKeysQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>
>;
export type GetApiAdminV1ConfigsKeysKeysQueryError = unknown;

export function useGetApiAdminV1ConfigsKeysKeys<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAdminV1ConfigsKeysKeys<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAdminV1ConfigsKeysKeys<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根据多个 key 获取配置
 */

export function useGetApiAdminV1ConfigsKeysKeys<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAdminV1ConfigsKeysKeysQueryOptions(
    keys,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiAdminV1ConfigsKeysKeysSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiAdminV1ConfigsKeysKeysQueryKey(keys);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>
  > = ({ signal }) =>
    getApiAdminV1ConfigsKeysKeys(keys, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAdminV1ConfigsKeysKeysSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>
>;
export type GetApiAdminV1ConfigsKeysKeysSuspenseQueryError = unknown;

export function useGetApiAdminV1ConfigsKeysKeysSuspense<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAdminV1ConfigsKeysKeysSuspense<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAdminV1ConfigsKeysKeysSuspense<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 根据多个 key 获取配置
 */

export function useGetApiAdminV1ConfigsKeysKeysSuspense<
  TData = Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
  TError = unknown,
>(
  keys: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiAdminV1ConfigsKeysKeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAdminV1ConfigsKeysKeysSuspenseQueryOptions(
    keys,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
