/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ClearParams,
  ListDramas1Params,
  ListRecentParams,
  ListVideosParams,
  PageDtoWatchHistoryDramaItemResponse,
  PageDtoWatchHistoryVideoItemResponse,
  ReportWatchHistoryRequest,
  ResultObject,
  ResultReportWatchHistoryResponse,
  ResultVoid,
  WatchHistoryRecentItemResponse,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type reportResponse200 = {
  data: ResultReportWatchHistoryResponse;
  status: 200;
};

export type reportResponse400 = {
  data: ResultObject;
  status: 400;
};

export type reportResponseSuccess = reportResponse200 & {
  headers: Headers;
};
export type reportResponseError = reportResponse400 & {
  headers: Headers;
};

export type reportResponse = reportResponseSuccess | reportResponseError;

export const getReportUrl = () => {
  return `/api/mini-drama/user/watch-history/report`;
};

/**
 * 用户点击进入播放时上报；单次最多 20 条，每条必填 episodeId 与 watchedAt（毫秒）。
 * watchedAt 允许相对服务器时间 ±5 分钟偏差。同批重复 episodeId 保留较大 watchedAt。
 * 短剧单集会同时更新短剧 Tab 与视频 Tab；独立短视频仅更新视频 Tab。
 * 成功返回 accepted 表示已接收，实际落库由 Kafka 异步完成。
 * @summary [鉴权]批量上报观看历史
 */
export const report = async (
  reportWatchHistoryRequest: ReportWatchHistoryRequest,
  options?: RequestInit,
): Promise<reportResponse> => {
  return appAxiosInstance<reportResponse>(getReportUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reportWatchHistoryRequest),
  });
};

export const getReportMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof report>>,
    TError,
    { data: ReportWatchHistoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof report>>,
  TError,
  { data: ReportWatchHistoryRequest },
  TContext
> => {
  const mutationKey = ['report'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof report>>,
    { data: ReportWatchHistoryRequest }
  > = (props) => {
    const { data } = props ?? {};

    return report(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReportMutationResult = NonNullable<
  Awaited<ReturnType<typeof report>>
>;
export type ReportMutationBody = ReportWatchHistoryRequest;
export type ReportMutationError = ResultObject;

/**
 * @summary [鉴权]批量上报观看历史
 */
export const useReport = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof report>>,
      TError,
      { data: ReportWatchHistoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof report>>,
  TError,
  { data: ReportWatchHistoryRequest },
  TContext
> => {
  return useMutation(getReportMutationOptions(options), queryClient);
};
export type listVideosResponse200 = {
  data: PageDtoWatchHistoryVideoItemResponse;
  status: 200;
};

export type listVideosResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listVideosResponseSuccess = listVideosResponse200 & {
  headers: Headers;
};
export type listVideosResponseError = listVideosResponse400 & {
  headers: Headers;
};

export type listVideosResponse =
  | listVideosResponseSuccess
  | listVideosResponseError;

export const getListVideosUrl = (params?: ListVideosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/watch-history/videos?${stringifiedParams}`
    : `/api/mini-drama/user/watch-history/videos`;
};

/**
 * 按最近观看时间倒序返回单集/短视频维度历史。
 * 短剧单集含 episodeNo 用于分集标签；下架内容仍展示，详情页由前端处理。
 * @summary [鉴权]视频观看历史列表
 */
export const listVideos = async (
  params?: ListVideosParams,
  options?: RequestInit,
): Promise<listVideosResponse> => {
  return appAxiosInstance<listVideosResponse>(getListVideosUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getListVideosQueryKey = (params?: ListVideosParams) => {
  return [
    `/api/mini-drama/user/watch-history/videos`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listVideos>>> = ({
    signal,
  }) => listVideos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVideos>>
>;
export type ListVideosQueryError = ResultObject;

export function useListVideos<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params: undefined | ListVideosParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVideos>>,
          TError,
          Awaited<ReturnType<typeof listVideos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVideos<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVideos>>,
          TError,
          Awaited<ReturnType<typeof listVideos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVideos<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]视频观看历史列表
 */

export function useListVideos<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListVideosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListVideosSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listVideos>>> = ({
    signal,
  }) => listVideos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListVideosSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVideos>>
>;
export type ListVideosSuspenseQueryError = ResultObject;

export function useListVideosSuspense<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params: undefined | ListVideosParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVideosSuspense<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVideosSuspense<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]视频观看历史列表
 */

export function useListVideosSuspense<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ResultObject,
>(
  params?: ListVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListVideosSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type listRecentResponse200 = {
  data: WatchHistoryRecentItemResponse[];
  status: 200;
};

export type listRecentResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listRecentResponseSuccess = listRecentResponse200 & {
  headers: Headers;
};
export type listRecentResponseError = listRecentResponse400 & {
  headers: Headers;
};

export type listRecentResponse =
  | listRecentResponseSuccess
  | listRecentResponseError;

export const getListRecentUrl = (params?: ListRecentParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/watch-history/recent?${stringifiedParams}`
    : `/api/mini-drama/user/watch-history/recent`;
};

/**
 * 按最近观看时间混排返回短剧续看卡与独立短视频，默认 3 条，供侧边栏/「我的」预览。
 * SHORT_DRAMA：来自短剧 Tab 聚合（每部短剧一条，含续看集与进度文案）。
 * SHORT_VIDEO：来自视频 Tab 中的独立短视频条目。
 * 短剧单集不会以单集卡片重复出现。不分页、无 mark。
 * @summary [鉴权]最近观看预览
 */
export const listRecent = async (
  params?: ListRecentParams,
  options?: RequestInit,
): Promise<listRecentResponse> => {
  return appAxiosInstance<listRecentResponse>(getListRecentUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getListRecentQueryKey = (params?: ListRecentParams) => {
  return [
    `/api/mini-drama/user/watch-history/recent`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListRecentQueryOptions = <
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listRecent>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListRecentQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecent>>> = ({
    signal,
  }) => listRecent(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listRecent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListRecentQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRecent>>
>;
export type ListRecentQueryError = ResultObject;

export function useListRecent<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params: undefined | ListRecentParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listRecent>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecent>>,
          TError,
          Awaited<ReturnType<typeof listRecent>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListRecent<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listRecent>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRecent>>,
          TError,
          Awaited<ReturnType<typeof listRecent>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListRecent<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listRecent>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]最近观看预览
 */

export function useListRecent<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listRecent>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListRecentQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListRecentSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listRecent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListRecentQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecent>>> = ({
    signal,
  }) => listRecent(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listRecent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListRecentSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRecent>>
>;
export type ListRecentSuspenseQueryError = ResultObject;

export function useListRecentSuspense<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params: undefined | ListRecentParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listRecent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListRecentSuspense<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listRecent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListRecentSuspense<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listRecent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]最近观看预览
 */

export function useListRecentSuspense<
  TData = Awaited<ReturnType<typeof listRecent>>,
  TError = ResultObject,
>(
  params?: ListRecentParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listRecent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListRecentSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type listDramas1Response200 = {
  data: PageDtoWatchHistoryDramaItemResponse;
  status: 200;
};

export type listDramas1Response400 = {
  data: ResultObject;
  status: 400;
};

export type listDramas1ResponseSuccess = listDramas1Response200 & {
  headers: Headers;
};
export type listDramas1ResponseError = listDramas1Response400 & {
  headers: Headers;
};

export type listDramas1Response =
  | listDramas1ResponseSuccess
  | listDramas1ResponseError;

export const getListDramas1Url = (params?: ListDramas1Params) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/watch-history/dramas?${stringifiedParams}`
    : `/api/mini-drama/user/watch-history/dramas`;
};

/**
 * 按最近观看时间倒序返回短剧维度历史，每部短剧一条，含续看集号与进度文案（如 3/44集）。
 * 侧边栏预览可使用 pageSize=3。分页游标 mark 格式：{lastWatchedAt}_{id}，首页不传。
 * @summary [鉴权]短剧观看历史列表
 */
export const listDramas1 = async (
  params?: ListDramas1Params,
  options?: RequestInit,
): Promise<listDramas1Response> => {
  return appAxiosInstance<listDramas1Response>(getListDramas1Url(params), {
    ...options,
    method: 'GET',
  });
};

export const getListDramas1QueryKey = (params?: ListDramas1Params) => {
  return [
    `/api/mini-drama/user/watch-history/dramas`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListDramas1QueryOptions = <
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDramas1>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDramas1QueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDramas1>>> = ({
    signal,
  }) => listDramas1(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDramas1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListDramas1QueryResult = NonNullable<
  Awaited<ReturnType<typeof listDramas1>>
>;
export type ListDramas1QueryError = ResultObject;

export function useListDramas1<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params: undefined | ListDramas1Params,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDramas1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDramas1>>,
          TError,
          Awaited<ReturnType<typeof listDramas1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListDramas1<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDramas1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDramas1>>,
          TError,
          Awaited<ReturnType<typeof listDramas1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListDramas1<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDramas1>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]短剧观看历史列表
 */

export function useListDramas1<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDramas1>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListDramas1QueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListDramas1SuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listDramas1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDramas1QueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDramas1>>> = ({
    signal,
  }) => listDramas1(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listDramas1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListDramas1SuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDramas1>>
>;
export type ListDramas1SuspenseQueryError = ResultObject;

export function useListDramas1Suspense<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params: undefined | ListDramas1Params,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listDramas1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListDramas1Suspense<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listDramas1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListDramas1Suspense<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listDramas1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]短剧观看历史列表
 */

export function useListDramas1Suspense<
  TData = Awaited<ReturnType<typeof listDramas1>>,
  TError = ResultObject,
>(
  params?: ListDramas1Params,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listDramas1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListDramas1SuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type clearResponse200 = {
  data: ResultVoid;
  status: 200;
};

export type clearResponse400 = {
  data: ResultObject;
  status: 400;
};

export type clearResponseSuccess = clearResponse200 & {
  headers: Headers;
};
export type clearResponseError = clearResponse400 & {
  headers: Headers;
};

export type clearResponse = clearResponseSuccess | clearResponseError;

export const getClearUrl = (params?: ClearParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/watch-history?${stringifiedParams}`
    : `/api/mini-drama/user/watch-history`;
};

/**
 * scope=ALL（默认）清空短剧+视频；DRAMA 仅短剧 Tab；VIDEO 仅视频 Tab。不可撤销。
 * @summary [鉴权]清空观看历史
 */
export const clear = async (
  params?: ClearParams,
  options?: RequestInit,
): Promise<clearResponse> => {
  return appAxiosInstance<clearResponse>(getClearUrl(params), {
    ...options,
    method: 'DELETE',
  });
};

export const getClearMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clear>>,
    TError,
    { params?: ClearParams },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clear>>,
  TError,
  { params?: ClearParams },
  TContext
> => {
  const mutationKey = ['clear'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clear>>,
    { params?: ClearParams }
  > = (props) => {
    const { params } = props ?? {};

    return clear(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClearMutationResult = NonNullable<
  Awaited<ReturnType<typeof clear>>
>;

export type ClearMutationError = ResultObject;

/**
 * @summary [鉴权]清空观看历史
 */
export const useClear = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clear>>,
      TError,
      { params?: ClearParams },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof clear>>,
  TError,
  { params?: ClearParams },
  TContext
> => {
  return useMutation(getClearMutationOptions(options), queryClient);
};
