/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ListReportTypesParams,
  ResultObject,
  ResultVoid,
  SubmitUgcReportRequest,
  UgcReportTypeItemResponse,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type reportWorkResponse200 = {
  data: ResultVoid;
  status: 200;
};

export type reportWorkResponse400 = {
  data: ResultObject;
  status: 400;
};

export type reportWorkResponseSuccess = reportWorkResponse200 & {
  headers: Headers;
};
export type reportWorkResponseError = reportWorkResponse400 & {
  headers: Headers;
};

export type reportWorkResponse =
  | reportWorkResponseSuccess
  | reportWorkResponseError;

export const getReportWorkUrl = (episodeId: number) => {
  return `/api/mini-drama/user/ugc/works/${episodeId}/report`;
};

/**
 * episodeId 为 drama_episode.id。短视频与短剧单集共用。频控：同对象 5 分钟冷却（127001）、每分钟 ≤3（127002）、每日 ≤10（127003，三类合计）。description 可选，最多 500 字。
 * @summary [鉴权]举报作品
 */
export const reportWork = async (
  episodeId: number,
  submitUgcReportRequest: SubmitUgcReportRequest,
  options?: RequestInit,
): Promise<reportWorkResponse> => {
  return appAxiosInstance<reportWorkResponse>(getReportWorkUrl(episodeId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitUgcReportRequest),
  });
};

export const getReportWorkMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reportWork>>,
    TError,
    { episodeId: number; data: SubmitUgcReportRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reportWork>>,
  TError,
  { episodeId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  const mutationKey = ['reportWork'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reportWork>>,
    { episodeId: number; data: SubmitUgcReportRequest }
  > = (props) => {
    const { episodeId, data } = props ?? {};

    return reportWork(episodeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReportWorkMutationResult = NonNullable<
  Awaited<ReturnType<typeof reportWork>>
>;
export type ReportWorkMutationBody = SubmitUgcReportRequest;
export type ReportWorkMutationError = ResultObject;

/**
 * @summary [鉴权]举报作品
 */
export const useReportWork = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reportWork>>,
      TError,
      { episodeId: number; data: SubmitUgcReportRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reportWork>>,
  TError,
  { episodeId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  return useMutation(getReportWorkMutationOptions(options), queryClient);
};
export type reportUserResponse200 = {
  data: ResultVoid;
  status: 200;
};

export type reportUserResponse400 = {
  data: ResultObject;
  status: 400;
};

export type reportUserResponseSuccess = reportUserResponse200 & {
  headers: Headers;
};
export type reportUserResponseError = reportUserResponse400 & {
  headers: Headers;
};

export type reportUserResponse =
  | reportUserResponseSuccess
  | reportUserResponseError;

export const getReportUserUrl = (userId: number) => {
  return `/api/mini-drama/user/ugc/users/${userId}/report`;
};

/**
 * 不能举报自己。原因列表请用 scope=USER（wallet 用户域原因集，含 other）。频控码同作品举报。
 * @summary [鉴权]举报用户
 */
export const reportUser = async (
  userId: number,
  submitUgcReportRequest: SubmitUgcReportRequest,
  options?: RequestInit,
): Promise<reportUserResponse> => {
  return appAxiosInstance<reportUserResponse>(getReportUserUrl(userId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitUgcReportRequest),
  });
};

export const getReportUserMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reportUser>>,
    TError,
    { userId: number; data: SubmitUgcReportRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reportUser>>,
  TError,
  { userId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  const mutationKey = ['reportUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reportUser>>,
    { userId: number; data: SubmitUgcReportRequest }
  > = (props) => {
    const { userId, data } = props ?? {};

    return reportUser(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReportUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof reportUser>>
>;
export type ReportUserMutationBody = SubmitUgcReportRequest;
export type ReportUserMutationError = ResultObject;

/**
 * @summary [鉴权]举报用户
 */
export const useReportUser = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reportUser>>,
      TError,
      { userId: number; data: SubmitUgcReportRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reportUser>>,
  TError,
  { userId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  return useMutation(getReportUserMutationOptions(options), queryClient);
};
export type reportDramaResponse200 = {
  data: ResultVoid;
  status: 200;
};

export type reportDramaResponse400 = {
  data: ResultObject;
  status: 400;
};

export type reportDramaResponseSuccess = reportDramaResponse200 & {
  headers: Headers;
};
export type reportDramaResponseError = reportDramaResponse400 & {
  headers: Headers;
};

export type reportDramaResponse =
  | reportDramaResponseSuccess
  | reportDramaResponseError;

export const getReportDramaUrl = (dramaId: number) => {
  return `/api/mini-drama/user/ugc/dramas/${dramaId}/report`;
};

/**
 * 仅 ONLINE 的 SHORT_DRAMA。与单集举报相互独立。频控码同作品举报。
 * @summary [鉴权]举报短剧
 */
export const reportDrama = async (
  dramaId: number,
  submitUgcReportRequest: SubmitUgcReportRequest,
  options?: RequestInit,
): Promise<reportDramaResponse> => {
  return appAxiosInstance<reportDramaResponse>(getReportDramaUrl(dramaId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitUgcReportRequest),
  });
};

export const getReportDramaMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reportDrama>>,
    TError,
    { dramaId: number; data: SubmitUgcReportRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reportDrama>>,
  TError,
  { dramaId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  const mutationKey = ['reportDrama'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reportDrama>>,
    { dramaId: number; data: SubmitUgcReportRequest }
  > = (props) => {
    const { dramaId, data } = props ?? {};

    return reportDrama(dramaId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReportDramaMutationResult = NonNullable<
  Awaited<ReturnType<typeof reportDrama>>
>;
export type ReportDramaMutationBody = SubmitUgcReportRequest;
export type ReportDramaMutationError = ResultObject;

/**
 * @summary [鉴权]举报短剧
 */
export const useReportDrama = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reportDrama>>,
      TError,
      { dramaId: number; data: SubmitUgcReportRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reportDrama>>,
  TError,
  { dramaId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  return useMutation(getReportDramaMutationOptions(options), queryClient);
};
export type reportCommentResponse200 = {
  data: ResultVoid;
  status: 200;
};

export type reportCommentResponse400 = {
  data: ResultObject;
  status: 400;
};

export type reportCommentResponseSuccess = reportCommentResponse200 & {
  headers: Headers;
};
export type reportCommentResponseError = reportCommentResponse400 & {
  headers: Headers;
};

export type reportCommentResponse =
  | reportCommentResponseSuccess
  | reportCommentResponseError;

export const getReportCommentUrl = (commentId: number) => {
  return `/api/mini-drama/user/ugc/comments/${commentId}/report`;
};

/**
 * 仅未删除且已过审评论。原因列表请用 scope=COMMENT（含 dislike，不含 quality_issue）。频控码同作品举报。
 * @summary [鉴权]举报评论
 */
export const reportComment = async (
  commentId: number,
  submitUgcReportRequest: SubmitUgcReportRequest,
  options?: RequestInit,
): Promise<reportCommentResponse> => {
  return appAxiosInstance<reportCommentResponse>(
    getReportCommentUrl(commentId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(submitUgcReportRequest),
    },
  );
};

export const getReportCommentMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reportComment>>,
    TError,
    { commentId: number; data: SubmitUgcReportRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reportComment>>,
  TError,
  { commentId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  const mutationKey = ['reportComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reportComment>>,
    { commentId: number; data: SubmitUgcReportRequest }
  > = (props) => {
    const { commentId, data } = props ?? {};

    return reportComment(commentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReportCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof reportComment>>
>;
export type ReportCommentMutationBody = SubmitUgcReportRequest;
export type ReportCommentMutationError = ResultObject;

/**
 * @summary [鉴权]举报评论
 */
export const useReportComment = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reportComment>>,
      TError,
      { commentId: number; data: SubmitUgcReportRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reportComment>>,
  TError,
  { commentId: number; data: SubmitUgcReportRequest },
  TContext
> => {
  return useMutation(getReportCommentMutationOptions(options), queryClient);
};
export type listReportTypesResponse200 = {
  data: UgcReportTypeItemResponse[];
  status: 200;
};

export type listReportTypesResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listReportTypesResponseSuccess = listReportTypesResponse200 & {
  headers: Headers;
};
export type listReportTypesResponseError = listReportTypesResponse400 & {
  headers: Headers;
};

export type listReportTypesResponse =
  | listReportTypesResponseSuccess
  | listReportTypesResponseError;

export const getListReportTypesUrl = (params?: ListReportTypesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/public/ugc/report-types?${stringifiedParams}`
    : `/api/mini-drama/public/ugc/report-types`;
};

/**
 * scope 可选：WORK / DRAMA / COMMENT / USER。不传返回全部启用原因。COMMENT 含 dislike（我不喜欢），不含 quality_issue；WORK/DRAMA 反之。USER 为 wallet 用户域专属原因集（如 impersonation、cyberbullying），不含内容通用原因。名称按 Accept-Language 本地化。
 * @summary [无鉴权]UGC 举报原因列表
 */
export const listReportTypes = async (
  params?: ListReportTypesParams,
  options?: RequestInit,
): Promise<listReportTypesResponse> => {
  return appAxiosInstance<listReportTypesResponse>(
    getListReportTypesUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getListReportTypesQueryKey = (params?: ListReportTypesParams) => {
  return [
    `/api/mini-drama/public/ugc/report-types`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListReportTypesQueryOptions = <
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListReportTypesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listReportTypes>>> = ({
    signal,
  }) => listReportTypes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listReportTypes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListReportTypesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listReportTypes>>
>;
export type ListReportTypesQueryError = ResultObject;

export function useListReportTypes<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params: undefined | ListReportTypesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReportTypes>>,
          TError,
          Awaited<ReturnType<typeof listReportTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReportTypes<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReportTypes>>,
          TError,
          Awaited<ReturnType<typeof listReportTypes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReportTypes<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]UGC 举报原因列表
 */

export function useListReportTypes<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListReportTypesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListReportTypesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListReportTypesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listReportTypes>>> = ({
    signal,
  }) => listReportTypes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listReportTypes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListReportTypesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listReportTypes>>
>;
export type ListReportTypesSuspenseQueryError = ResultObject;

export function useListReportTypesSuspense<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params: undefined | ListReportTypesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReportTypesSuspense<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReportTypesSuspense<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]UGC 举报原因列表
 */

export function useListReportTypesSuspense<
  TData = Awaited<ReturnType<typeof listReportTypes>>,
  TError = ResultObject,
>(
  params?: ListReportTypesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listReportTypes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListReportTypesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
