/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ManualScrapeResponse,
  ResultObject,
  ShareAttemptListResponse,
  ShareAttemptResponse,
  SubmitShareAttemptRequest,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listShareAttemptsResponse200 = {
  data: ShareAttemptListResponse;
  status: 200;
};

export type listShareAttemptsResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listShareAttemptsResponse405 = {
  data: ResultObject;
  status: 405;
};

export type listShareAttemptsResponse500 = {
  data: ResultObject;
  status: 500;
};

export type listShareAttemptsResponseSuccess = listShareAttemptsResponse200 & {
  headers: Headers;
};
export type listShareAttemptsResponseError = (
  | listShareAttemptsResponse400
  | listShareAttemptsResponse405
  | listShareAttemptsResponse500
) & {
  headers: Headers;
};

export type listShareAttemptsResponse =
  | listShareAttemptsResponseSuccess
  | listShareAttemptsResponseError;

export const getListShareAttemptsUrl = (activityId: number) => {
  return `/api/activity/activities/${activityId}/shareAttempts`;
};

/**
 * 查询当前用户在某活动下所有平台（x / tiktok / youtube）的最新 attempt 状态（每平台至多一条），并返回本活动配置的传播数据积分规则（每 10 播放 / 10 点赞 / 10 转推 加多少分），供前端展示。
 * @summary 查询所有平台的分享 attempt 状态
 */
export const listShareAttempts = async (
  activityId: number,
  options?: RequestInit,
): Promise<listShareAttemptsResponse> => {
  return appAxiosInstance<listShareAttemptsResponse>(
    getListShareAttemptsUrl(activityId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getListShareAttemptsQueryKey = (activityId: number) => {
  return [`/api/activity/activities/${activityId}/shareAttempts`] as const;
};

export const getListShareAttemptsQueryOptions = <
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListShareAttemptsQueryKey(activityId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listShareAttempts>>
  > = ({ signal }) =>
    listShareAttempts(activityId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: activityId !== null && activityId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listShareAttempts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListShareAttemptsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listShareAttempts>>
>;
export type ListShareAttemptsQueryError = ResultObject;

export function useListShareAttempts<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShareAttempts>>,
          TError,
          Awaited<ReturnType<typeof listShareAttempts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListShareAttempts<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listShareAttempts>>,
          TError,
          Awaited<ReturnType<typeof listShareAttempts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListShareAttempts<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询所有平台的分享 attempt 状态
 */

export function useListShareAttempts<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListShareAttemptsQueryOptions(activityId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListShareAttemptsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListShareAttemptsQueryKey(activityId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listShareAttempts>>
  > = ({ signal }) =>
    listShareAttempts(activityId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listShareAttempts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListShareAttemptsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listShareAttempts>>
>;
export type ListShareAttemptsSuspenseQueryError = ResultObject;

export function useListShareAttemptsSuspense<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListShareAttemptsSuspense<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListShareAttemptsSuspense<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询所有平台的分享 attempt 状态
 */

export function useListShareAttemptsSuspense<
  TData = Awaited<ReturnType<typeof listShareAttempts>>,
  TError = ResultObject,
>(
  activityId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listShareAttempts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListShareAttemptsSuspenseQueryOptions(
    activityId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type submitShareAttemptResponse200 = {
  data: ShareAttemptResponse;
  status: 200;
};

export type submitShareAttemptResponse400 = {
  data: ResultObject;
  status: 400;
};

export type submitShareAttemptResponse405 = {
  data: ResultObject;
  status: 405;
};

export type submitShareAttemptResponse500 = {
  data: ResultObject;
  status: 500;
};

export type submitShareAttemptResponseSuccess =
  submitShareAttemptResponse200 & {
    headers: Headers;
  };
export type submitShareAttemptResponseError = (
  | submitShareAttemptResponse400
  | submitShareAttemptResponse405
  | submitShareAttemptResponse500
) & {
  headers: Headers;
};

export type submitShareAttemptResponse =
  | submitShareAttemptResponseSuccess
  | submitShareAttemptResponseError;

export const getSubmitShareAttemptUrl = (activityId: number) => {
  return `/api/activity/activities/${activityId}/shareAttempts`;
};

/**
 * 提交当前用户在某活动下的分享 attempt，平台维度（x / tiktok / youtube）一次性约束：
 * - 同平台存在 pending_approval 或 approved 记录 → 拒绝
 * - 同平台存在 rejected 记录 → 允许重新提交（生成新 attemptId + code）
 * @summary 提交分享 attempt
 */
export const submitShareAttempt = async (
  activityId: number,
  submitShareAttemptRequest: SubmitShareAttemptRequest,
  options?: RequestInit,
): Promise<submitShareAttemptResponse> => {
  return appAxiosInstance<submitShareAttemptResponse>(
    getSubmitShareAttemptUrl(activityId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(submitShareAttemptRequest),
    },
  );
};

export const getSubmitShareAttemptMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitShareAttempt>>,
    TError,
    { activityId: number; data: SubmitShareAttemptRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitShareAttempt>>,
  TError,
  { activityId: number; data: SubmitShareAttemptRequest },
  TContext
> => {
  const mutationKey = ['submitShareAttempt'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitShareAttempt>>,
    { activityId: number; data: SubmitShareAttemptRequest }
  > = (props) => {
    const { activityId, data } = props ?? {};

    return submitShareAttempt(activityId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitShareAttemptMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitShareAttempt>>
>;
export type SubmitShareAttemptMutationBody = SubmitShareAttemptRequest;
export type SubmitShareAttemptMutationError = ResultObject;

/**
 * @summary 提交分享 attempt
 */
export const useSubmitShareAttempt = <
  TError = ResultObject,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitShareAttempt>>,
      TError,
      { activityId: number; data: SubmitShareAttemptRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitShareAttempt>>,
  TError,
  { activityId: number; data: SubmitShareAttemptRequest },
  TContext
> => {
  return useMutation(
    getSubmitShareAttemptMutationOptions(options),
    queryClient,
  );
};
export type scrapeMyShareAttemptsResponse200 = {
  data: ManualScrapeResponse;
  status: 200;
};

export type scrapeMyShareAttemptsResponse400 = {
  data: ResultObject;
  status: 400;
};

export type scrapeMyShareAttemptsResponse405 = {
  data: ResultObject;
  status: 405;
};

export type scrapeMyShareAttemptsResponse500 = {
  data: ResultObject;
  status: 500;
};

export type scrapeMyShareAttemptsResponseSuccess =
  scrapeMyShareAttemptsResponse200 & {
    headers: Headers;
  };
export type scrapeMyShareAttemptsResponseError = (
  | scrapeMyShareAttemptsResponse400
  | scrapeMyShareAttemptsResponse405
  | scrapeMyShareAttemptsResponse500
) & {
  headers: Headers;
};

export type scrapeMyShareAttemptsResponse =
  | scrapeMyShareAttemptsResponseSuccess
  | scrapeMyShareAttemptsResponseError;

export const getScrapeMyShareAttemptsUrl = (activityId: number) => {
  return `/api/activity/activities/${activityId}/shareAttempts/scrape`;
};

/**
 * 抓取当前用户在该活动下所有 approved attempt 的传播数据（播放/点赞/转推），按活动配置的 shareMetricsPointsRules 现算积分，返回每条 attempt 的明细 + 聚合总积分；若总积分 > 0 则发出 FINAL_POINTS_SNAPSHOT 事件（与结算共用幂等键，不会重复入账）。
 * @summary 手动触发爬虫（测试用）
 */
export const scrapeMyShareAttempts = async (
  activityId: number,
  options?: RequestInit,
): Promise<scrapeMyShareAttemptsResponse> => {
  return appAxiosInstance<scrapeMyShareAttemptsResponse>(
    getScrapeMyShareAttemptsUrl(activityId),
    {
      ...options,
      method: 'POST',
    },
  );
};

export const getScrapeMyShareAttemptsMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof scrapeMyShareAttempts>>,
    TError,
    { activityId: number },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof scrapeMyShareAttempts>>,
  TError,
  { activityId: number },
  TContext
> => {
  const mutationKey = ['scrapeMyShareAttempts'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof scrapeMyShareAttempts>>,
    { activityId: number }
  > = (props) => {
    const { activityId } = props ?? {};

    return scrapeMyShareAttempts(activityId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ScrapeMyShareAttemptsMutationResult = NonNullable<
  Awaited<ReturnType<typeof scrapeMyShareAttempts>>
>;

export type ScrapeMyShareAttemptsMutationError = ResultObject;

/**
 * @summary 手动触发爬虫（测试用）
 */
export const useScrapeMyShareAttempts = <
  TError = ResultObject,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof scrapeMyShareAttempts>>,
      TError,
      { activityId: number },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof scrapeMyShareAttempts>>,
  TError,
  { activityId: number },
  TContext
> => {
  return useMutation(
    getScrapeMyShareAttemptsMutationOptions(options),
    queryClient,
  );
};
