/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  AddEpisodeToCollection200,
  CollectionDetailResponse,
  CollectionEpisodeActionRequest,
  CollectionListItemResponse,
  CreateCollectionRequest,
  DeleteCollection200,
  ListAddableEpisodesParams,
  ListCollectionsParams,
  RemoveEpisodeFromCollection200,
  ResultObject,
  ShortVideoListItemResponse,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCollectionResponse200 = {
  data: CollectionDetailResponse;
  status: 200;
};

export type getCollectionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type getCollectionResponseSuccess = getCollectionResponse200 & {
  headers: Headers;
};
export type getCollectionResponseError = getCollectionResponse400 & {
  headers: Headers;
};

export type getCollectionResponse =
  | getCollectionResponseSuccess
  | getCollectionResponseError;

export const getGetCollectionUrl = (collectionId: number) => {
  return `/api/mini-drama/creator/drama-collections/${collectionId}`;
};

/**
 * @summary [鉴权]合集详情
 */
export const getCollection = async (
  collectionId: number,
  options?: RequestInit,
): Promise<getCollectionResponse> => {
  return appAxiosInstance<getCollectionResponse>(
    getGetCollectionUrl(collectionId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetCollectionQueryKey = (collectionId: number) => {
  return [`/api/mini-drama/creator/drama-collections/${collectionId}`] as const;
};

export const getGetCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCollectionQueryKey(collectionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollection>>> = ({
    signal,
  }) => getCollection(collectionId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: collectionId !== null && collectionId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCollection>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCollection>>
>;
export type GetCollectionQueryError = ResultObject;

export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollection>>,
          TError,
          Awaited<ReturnType<typeof getCollection>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollection>>,
          TError,
          Awaited<ReturnType<typeof getCollection>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]合集详情
 */

export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCollectionQueryOptions(collectionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetCollectionSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCollectionQueryKey(collectionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollection>>> = ({
    signal,
  }) => getCollection(collectionId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCollection>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollectionSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCollection>>
>;
export type GetCollectionSuspenseQueryError = ResultObject;

export function useGetCollectionSuspense<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollectionSuspense<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollectionSuspense<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]合集详情
 */

export function useGetCollectionSuspense<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ResultObject,
>(
  collectionId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCollectionSuspenseQueryOptions(
    collectionId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateCollectionResponse200 = {
  data: CollectionDetailResponse;
  status: 200;
};

export type updateCollectionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type updateCollectionResponseSuccess = updateCollectionResponse200 & {
  headers: Headers;
};
export type updateCollectionResponseError = updateCollectionResponse400 & {
  headers: Headers;
};

export type updateCollectionResponse =
  | updateCollectionResponseSuccess
  | updateCollectionResponseError;

export const getUpdateCollectionUrl = (collectionId: number) => {
  return `/api/mini-drama/creator/drama-collections/${collectionId}`;
};

/**
 * @summary [鉴权]编辑合集
 */
export const updateCollection = async (
  collectionId: number,
  createCollectionRequest: CreateCollectionRequest,
  options?: RequestInit,
): Promise<updateCollectionResponse> => {
  return appAxiosInstance<updateCollectionResponse>(
    getUpdateCollectionUrl(collectionId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createCollectionRequest),
    },
  );
};

export const getUpdateCollectionMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCollection>>,
    TError,
    { collectionId: number; data: CreateCollectionRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCollection>>,
  TError,
  { collectionId: number; data: CreateCollectionRequest },
  TContext
> => {
  const mutationKey = ['updateCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCollection>>,
    { collectionId: number; data: CreateCollectionRequest }
  > = (props) => {
    const { collectionId, data } = props ?? {};

    return updateCollection(collectionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCollection>>
>;
export type UpdateCollectionMutationBody = CreateCollectionRequest;
export type UpdateCollectionMutationError = ResultObject;

/**
 * @summary [鉴权]编辑合集
 */
export const useUpdateCollection = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCollection>>,
      TError,
      { collectionId: number; data: CreateCollectionRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCollection>>,
  TError,
  { collectionId: number; data: CreateCollectionRequest },
  TContext
> => {
  return useMutation(getUpdateCollectionMutationOptions(options), queryClient);
};
export type deleteCollectionResponse200 = {
  data: DeleteCollection200;
  status: 200;
};

export type deleteCollectionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type deleteCollectionResponseSuccess = deleteCollectionResponse200 & {
  headers: Headers;
};
export type deleteCollectionResponseError = deleteCollectionResponse400 & {
  headers: Headers;
};

export type deleteCollectionResponse =
  | deleteCollectionResponseSuccess
  | deleteCollectionResponseError;

export const getDeleteCollectionUrl = (collectionId: number) => {
  return `/api/mini-drama/creator/drama-collections/${collectionId}`;
};

/**
 * @summary [鉴权]删除合集(成员解绑, 自身软删)
 */
export const deleteCollection = async (
  collectionId: number,
  options?: RequestInit,
): Promise<deleteCollectionResponse> => {
  return appAxiosInstance<deleteCollectionResponse>(
    getDeleteCollectionUrl(collectionId),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getDeleteCollectionMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCollection>>,
    TError,
    { collectionId: number },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCollection>>,
  TError,
  { collectionId: number },
  TContext
> => {
  const mutationKey = ['deleteCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCollection>>,
    { collectionId: number }
  > = (props) => {
    const { collectionId } = props ?? {};

    return deleteCollection(collectionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCollection>>
>;

export type DeleteCollectionMutationError = ResultObject;

/**
 * @summary [鉴权]删除合集(成员解绑, 自身软删)
 */
export const useDeleteCollection = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCollection>>,
      TError,
      { collectionId: number },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCollection>>,
  TError,
  { collectionId: number },
  TContext
> => {
  return useMutation(getDeleteCollectionMutationOptions(options), queryClient);
};
export type listCollectionsResponse200 = {
  data: CollectionListItemResponse[];
  status: 200;
};

export type listCollectionsResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listCollectionsResponseSuccess = listCollectionsResponse200 & {
  headers: Headers;
};
export type listCollectionsResponseError = listCollectionsResponse400 & {
  headers: Headers;
};

export type listCollectionsResponse =
  | listCollectionsResponseSuccess
  | listCollectionsResponseError;

export const getListCollectionsUrl = (params?: ListCollectionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/creator/drama-collections?${stringifiedParams}`
    : `/api/mini-drama/creator/drama-collections`;
};

/**
 * @summary [鉴权]我创建的合集列表
 */
export const listCollections = async (
  params?: ListCollectionsParams,
  options?: RequestInit,
): Promise<listCollectionsResponse> => {
  return appAxiosInstance<listCollectionsResponse>(
    getListCollectionsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getListCollectionsQueryKey = (params?: ListCollectionsParams) => {
  return [
    `/api/mini-drama/creator/drama-collections`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCollectionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCollections>>> = ({
    signal,
  }) => listCollections(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListCollectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCollections>>
>;
export type ListCollectionsQueryError = ResultObject;

export function useListCollections<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params: undefined | ListCollectionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCollections>>,
          TError,
          Awaited<ReturnType<typeof listCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCollections<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCollections>>,
          TError,
          Awaited<ReturnType<typeof listCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCollections<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]我创建的合集列表
 */

export function useListCollections<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListCollectionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListCollectionsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCollectionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCollections>>> = ({
    signal,
  }) => listCollections(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListCollectionsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCollections>>
>;
export type ListCollectionsSuspenseQueryError = ResultObject;

export function useListCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params: undefined | ListCollectionsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]我创建的合集列表
 */

export function useListCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listCollections>>,
  TError = ResultObject,
>(
  params?: ListCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListCollectionsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createCollectionResponse200 = {
  data: CollectionDetailResponse;
  status: 200;
};

export type createCollectionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type createCollectionResponseSuccess = createCollectionResponse200 & {
  headers: Headers;
};
export type createCollectionResponseError = createCollectionResponse400 & {
  headers: Headers;
};

export type createCollectionResponse =
  | createCollectionResponseSuccess
  | createCollectionResponseError;

export const getCreateCollectionUrl = () => {
  return `/api/mini-drama/creator/drama-collections`;
};

/**
 * @summary [鉴权]创建合集(创建即上线, 不审核)
 */
export const createCollection = async (
  createCollectionRequest: CreateCollectionRequest,
  options?: RequestInit,
): Promise<createCollectionResponse> => {
  return appAxiosInstance<createCollectionResponse>(getCreateCollectionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCollectionRequest),
  });
};

export const getCreateCollectionMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCollection>>,
    TError,
    { data: CreateCollectionRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCollection>>,
  TError,
  { data: CreateCollectionRequest },
  TContext
> => {
  const mutationKey = ['createCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCollection>>,
    { data: CreateCollectionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCollection>>
>;
export type CreateCollectionMutationBody = CreateCollectionRequest;
export type CreateCollectionMutationError = ResultObject;

/**
 * @summary [鉴权]创建合集(创建即上线, 不审核)
 */
export const useCreateCollection = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCollection>>,
      TError,
      { data: CreateCollectionRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCollection>>,
  TError,
  { data: CreateCollectionRequest },
  TContext
> => {
  return useMutation(getCreateCollectionMutationOptions(options), queryClient);
};
export type addEpisodeToCollectionResponse200 = {
  data: AddEpisodeToCollection200;
  status: 200;
};

export type addEpisodeToCollectionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type addEpisodeToCollectionResponseSuccess =
  addEpisodeToCollectionResponse200 & {
    headers: Headers;
  };
export type addEpisodeToCollectionResponseError =
  addEpisodeToCollectionResponse400 & {
    headers: Headers;
  };

export type addEpisodeToCollectionResponse =
  | addEpisodeToCollectionResponseSuccess
  | addEpisodeToCollectionResponseError;

export const getAddEpisodeToCollectionUrl = (collectionId: number) => {
  return `/api/mini-drama/creator/drama-collections/${collectionId}/episodes`;
};

/**
 * @summary [鉴权]添加短视频到合集
 */
export const addEpisodeToCollection = async (
  collectionId: number,
  collectionEpisodeActionRequest: CollectionEpisodeActionRequest,
  options?: RequestInit,
): Promise<addEpisodeToCollectionResponse> => {
  return appAxiosInstance<addEpisodeToCollectionResponse>(
    getAddEpisodeToCollectionUrl(collectionId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(collectionEpisodeActionRequest),
    },
  );
};

export const getAddEpisodeToCollectionMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addEpisodeToCollection>>,
    TError,
    { collectionId: number; data: CollectionEpisodeActionRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addEpisodeToCollection>>,
  TError,
  { collectionId: number; data: CollectionEpisodeActionRequest },
  TContext
> => {
  const mutationKey = ['addEpisodeToCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addEpisodeToCollection>>,
    { collectionId: number; data: CollectionEpisodeActionRequest }
  > = (props) => {
    const { collectionId, data } = props ?? {};

    return addEpisodeToCollection(collectionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddEpisodeToCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof addEpisodeToCollection>>
>;
export type AddEpisodeToCollectionMutationBody = CollectionEpisodeActionRequest;
export type AddEpisodeToCollectionMutationError = ResultObject;

/**
 * @summary [鉴权]添加短视频到合集
 */
export const useAddEpisodeToCollection = <
  TError = ResultObject,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addEpisodeToCollection>>,
      TError,
      { collectionId: number; data: CollectionEpisodeActionRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addEpisodeToCollection>>,
  TError,
  { collectionId: number; data: CollectionEpisodeActionRequest },
  TContext
> => {
  return useMutation(
    getAddEpisodeToCollectionMutationOptions(options),
    queryClient,
  );
};
export type listAddableEpisodesResponse200 = {
  data: ShortVideoListItemResponse[];
  status: 200;
};

export type listAddableEpisodesResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listAddableEpisodesResponseSuccess =
  listAddableEpisodesResponse200 & {
    headers: Headers;
  };
export type listAddableEpisodesResponseError =
  listAddableEpisodesResponse400 & {
    headers: Headers;
  };

export type listAddableEpisodesResponse =
  | listAddableEpisodesResponseSuccess
  | listAddableEpisodesResponseError;

export const getListAddableEpisodesUrl = (
  collectionId: number,
  params?: ListAddableEpisodesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/creator/drama-collections/${collectionId}/addable?${stringifiedParams}`
    : `/api/mini-drama/creator/drama-collections/${collectionId}/addable`;
};

/**
 * @summary [鉴权]可加入合集的短视频列表(drama_id 为空)
 */
export const listAddableEpisodes = async (
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: RequestInit,
): Promise<listAddableEpisodesResponse> => {
  return appAxiosInstance<listAddableEpisodesResponse>(
    getListAddableEpisodesUrl(collectionId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getListAddableEpisodesQueryKey = (
  collectionId: number,
  params?: ListAddableEpisodesParams,
) => {
  return [
    `/api/mini-drama/creator/drama-collections/${collectionId}/addable`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListAddableEpisodesQueryOptions = <
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListAddableEpisodesQueryKey(collectionId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAddableEpisodes>>
  > = ({ signal }) =>
    listAddableEpisodes(collectionId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: collectionId !== null && collectionId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listAddableEpisodes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAddableEpisodesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAddableEpisodes>>
>;
export type ListAddableEpisodesQueryError = ResultObject;

export function useListAddableEpisodes<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params: undefined | ListAddableEpisodesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAddableEpisodes>>,
          TError,
          Awaited<ReturnType<typeof listAddableEpisodes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAddableEpisodes<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAddableEpisodes>>,
          TError,
          Awaited<ReturnType<typeof listAddableEpisodes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAddableEpisodes<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]可加入合集的短视频列表(drama_id 为空)
 */

export function useListAddableEpisodes<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListAddableEpisodesQueryOptions(
    collectionId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListAddableEpisodesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListAddableEpisodesQueryKey(collectionId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAddableEpisodes>>
  > = ({ signal }) =>
    listAddableEpisodes(collectionId, params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listAddableEpisodes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAddableEpisodesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAddableEpisodes>>
>;
export type ListAddableEpisodesSuspenseQueryError = ResultObject;

export function useListAddableEpisodesSuspense<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params: undefined | ListAddableEpisodesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAddableEpisodesSuspense<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAddableEpisodesSuspense<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]可加入合集的短视频列表(drama_id 为空)
 */

export function useListAddableEpisodesSuspense<
  TData = Awaited<ReturnType<typeof listAddableEpisodes>>,
  TError = ResultObject,
>(
  collectionId: number,
  params?: ListAddableEpisodesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listAddableEpisodes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListAddableEpisodesSuspenseQueryOptions(
    collectionId,
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type removeEpisodeFromCollectionResponse200 = {
  data: RemoveEpisodeFromCollection200;
  status: 200;
};

export type removeEpisodeFromCollectionResponse400 = {
  data: ResultObject;
  status: 400;
};

export type removeEpisodeFromCollectionResponseSuccess =
  removeEpisodeFromCollectionResponse200 & {
    headers: Headers;
  };
export type removeEpisodeFromCollectionResponseError =
  removeEpisodeFromCollectionResponse400 & {
    headers: Headers;
  };

export type removeEpisodeFromCollectionResponse =
  | removeEpisodeFromCollectionResponseSuccess
  | removeEpisodeFromCollectionResponseError;

export const getRemoveEpisodeFromCollectionUrl = (
  collectionId: number,
  episodeId: number,
) => {
  return `/api/mini-drama/creator/drama-collections/${collectionId}/episodes/${episodeId}`;
};

/**
 * @summary [鉴权]从合集移除短视频
 */
export const removeEpisodeFromCollection = async (
  collectionId: number,
  episodeId: number,
  options?: RequestInit,
): Promise<removeEpisodeFromCollectionResponse> => {
  return appAxiosInstance<removeEpisodeFromCollectionResponse>(
    getRemoveEpisodeFromCollectionUrl(collectionId, episodeId),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getRemoveEpisodeFromCollectionMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeEpisodeFromCollection>>,
    TError,
    { collectionId: number; episodeId: number },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeEpisodeFromCollection>>,
  TError,
  { collectionId: number; episodeId: number },
  TContext
> => {
  const mutationKey = ['removeEpisodeFromCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeEpisodeFromCollection>>,
    { collectionId: number; episodeId: number }
  > = (props) => {
    const { collectionId, episodeId } = props ?? {};

    return removeEpisodeFromCollection(collectionId, episodeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveEpisodeFromCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeEpisodeFromCollection>>
>;

export type RemoveEpisodeFromCollectionMutationError = ResultObject;

/**
 * @summary [鉴权]从合集移除短视频
 */
export const useRemoveEpisodeFromCollection = <
  TError = ResultObject,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeEpisodeFromCollection>>,
      TError,
      { collectionId: number; episodeId: number },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeEpisodeFromCollection>>,
  TError,
  { collectionId: number; episodeId: number },
  TContext
> => {
  return useMutation(
    getRemoveEpisodeFromCollectionMutationOptions(options),
    queryClient,
  );
};
