/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ActorCollectionsParams,
  DramasParams,
  FavoritesParams,
  LikesParams,
  PageDtoActorCollectionResponse,
  PageDtoUserProfileUnifiedResponse,
  ResultObject,
  WorksParams,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type worksResponse200 = {
  data: PageDtoUserProfileUnifiedResponse;
  status: 200;
};

export type worksResponse400 = {
  data: ResultObject;
  status: 400;
};

export type worksResponseSuccess = worksResponse200 & {
  headers: Headers;
};
export type worksResponseError = worksResponse400 & {
  headers: Headers;
};

export type worksResponse = worksResponseSuccess | worksResponseError;

export const getWorksUrl = (userId: number, params?: WorksParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/profiles/${userId}/works?${stringifiedParams}`
    : `/api/mini-drama/user/profiles/${userId}/works`;
};

/**
 * @summary [鉴权]作品列表
 */
export const works = async (
  userId: number,
  params?: WorksParams,
  options?: RequestInit,
): Promise<worksResponse> => {
  return appAxiosInstance<worksResponse>(getWorksUrl(userId, params), {
    ...options,
    method: 'GET',
  });
};

export const getWorksQueryKey = (userId: number, params?: WorksParams) => {
  return [
    `/api/mini-drama/user/profiles/${userId}/works`,
    ...(params ? [params] : []),
  ] as const;
};

export const getWorksQueryOptions = <
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWorksQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof works>>> = ({
    signal,
  }) => works(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type WorksQueryResult = NonNullable<Awaited<ReturnType<typeof works>>>;
export type WorksQueryError = ResultObject;

export function useWorks<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | WorksParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof works>>,
          TError,
          Awaited<ReturnType<typeof works>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorks<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof works>>,
          TError,
          Awaited<ReturnType<typeof works>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorks<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]作品列表
 */

export function useWorks<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getWorksQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getWorksSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWorksQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof works>>> = ({
    signal,
  }) => works(userId, params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof works>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WorksSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof works>>
>;
export type WorksSuspenseQueryError = ResultObject;

export function useWorksSuspense<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | WorksParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorksSuspense<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorksSuspense<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]作品列表
 */

export function useWorksSuspense<
  TData = Awaited<ReturnType<typeof works>>,
  TError = ResultObject,
>(
  userId: number,
  params?: WorksParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof works>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getWorksSuspenseQueryOptions(userId, params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type likesResponse200 = {
  data: PageDtoUserProfileUnifiedResponse;
  status: 200;
};

export type likesResponse400 = {
  data: ResultObject;
  status: 400;
};

export type likesResponseSuccess = likesResponse200 & {
  headers: Headers;
};
export type likesResponseError = likesResponse400 & {
  headers: Headers;
};

export type likesResponse = likesResponseSuccess | likesResponseError;

export const getLikesUrl = (userId: number, params?: LikesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/profiles/${userId}/likes?${stringifiedParams}`
    : `/api/mini-drama/user/profiles/${userId}/likes`;
};

/**
 * @summary [鉴权]点赞
 */
export const likes = async (
  userId: number,
  params?: LikesParams,
  options?: RequestInit,
): Promise<likesResponse> => {
  return appAxiosInstance<likesResponse>(getLikesUrl(userId, params), {
    ...options,
    method: 'GET',
  });
};

export const getLikesQueryKey = (userId: number, params?: LikesParams) => {
  return [
    `/api/mini-drama/user/profiles/${userId}/likes`,
    ...(params ? [params] : []),
  ] as const;
};

export const getLikesQueryOptions = <
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLikesQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof likes>>> = ({
    signal,
  }) => likes(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type LikesQueryResult = NonNullable<Awaited<ReturnType<typeof likes>>>;
export type LikesQueryError = ResultObject;

export function useLikes<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | LikesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof likes>>,
          TError,
          Awaited<ReturnType<typeof likes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLikes<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof likes>>,
          TError,
          Awaited<ReturnType<typeof likes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLikes<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]点赞
 */

export function useLikes<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLikesQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getLikesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLikesQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof likes>>> = ({
    signal,
  }) => likes(userId, params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof likes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LikesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof likes>>
>;
export type LikesSuspenseQueryError = ResultObject;

export function useLikesSuspense<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | LikesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLikesSuspense<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLikesSuspense<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]点赞
 */

export function useLikesSuspense<
  TData = Awaited<ReturnType<typeof likes>>,
  TError = ResultObject,
>(
  userId: number,
  params?: LikesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof likes>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLikesSuspenseQueryOptions(userId, params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type favoritesResponse200 = {
  data: PageDtoUserProfileUnifiedResponse;
  status: 200;
};

export type favoritesResponse400 = {
  data: ResultObject;
  status: 400;
};

export type favoritesResponseSuccess = favoritesResponse200 & {
  headers: Headers;
};
export type favoritesResponseError = favoritesResponse400 & {
  headers: Headers;
};

export type favoritesResponse =
  | favoritesResponseSuccess
  | favoritesResponseError;

export const getFavoritesUrl = (userId: number, params: FavoritesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/profiles/${userId}/favorites?${stringifiedParams}`
    : `/api/mini-drama/user/profiles/${userId}/favorites`;
};

/**
 * @summary [鉴权]收藏
 */
export const favorites = async (
  userId: number,
  params: FavoritesParams,
  options?: RequestInit,
): Promise<favoritesResponse> => {
  return appAxiosInstance<favoritesResponse>(getFavoritesUrl(userId, params), {
    ...options,
    method: 'GET',
  });
};

export const getFavoritesQueryKey = (
  userId: number,
  params?: FavoritesParams,
) => {
  return [
    `/api/mini-drama/user/profiles/${userId}/favorites`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFavoritesQueryOptions = <
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof favorites>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFavoritesQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof favorites>>> = ({
    signal,
  }) => favorites(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof favorites>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FavoritesQueryResult = NonNullable<
  Awaited<ReturnType<typeof favorites>>
>;
export type FavoritesQueryError = ResultObject;

export function useFavorites<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof favorites>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof favorites>>,
          TError,
          Awaited<ReturnType<typeof favorites>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavorites<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof favorites>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof favorites>>,
          TError,
          Awaited<ReturnType<typeof favorites>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavorites<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof favorites>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]收藏
 */

export function useFavorites<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof favorites>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFavoritesQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getFavoritesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof favorites>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFavoritesQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof favorites>>> = ({
    signal,
  }) => favorites(userId, params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof favorites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof favorites>>
>;
export type FavoritesSuspenseQueryError = ResultObject;

export function useFavoritesSuspense<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof favorites>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavoritesSuspense<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof favorites>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavoritesSuspense<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof favorites>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]收藏
 */

export function useFavoritesSuspense<
  TData = Awaited<ReturnType<typeof favorites>>,
  TError = ResultObject,
>(
  userId: number,
  params: FavoritesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof favorites>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFavoritesSuspenseQueryOptions(
    userId,
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type dramasResponse200 = {
  data: PageDtoUserProfileUnifiedResponse;
  status: 200;
};

export type dramasResponse400 = {
  data: ResultObject;
  status: 400;
};

export type dramasResponseSuccess = dramasResponse200 & {
  headers: Headers;
};
export type dramasResponseError = dramasResponse400 & {
  headers: Headers;
};

export type dramasResponse = dramasResponseSuccess | dramasResponseError;

export const getDramasUrl = (userId: number, params?: DramasParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/profiles/${userId}/dramas?${stringifiedParams}`
    : `/api/mini-drama/user/profiles/${userId}/dramas`;
};

/**
 * @summary [鉴权]短剧列表
 */
export const dramas = async (
  userId: number,
  params?: DramasParams,
  options?: RequestInit,
): Promise<dramasResponse> => {
  return appAxiosInstance<dramasResponse>(getDramasUrl(userId, params), {
    ...options,
    method: 'GET',
  });
};

export const getDramasQueryKey = (userId: number, params?: DramasParams) => {
  return [
    `/api/mini-drama/user/profiles/${userId}/dramas`,
    ...(params ? [params] : []),
  ] as const;
};

export const getDramasQueryOptions = <
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDramasQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dramas>>> = ({
    signal,
  }) => dramas(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type DramasQueryResult = NonNullable<Awaited<ReturnType<typeof dramas>>>;
export type DramasQueryError = ResultObject;

export function useDramas<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | DramasParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dramas>>,
          TError,
          Awaited<ReturnType<typeof dramas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDramas<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dramas>>,
          TError,
          Awaited<ReturnType<typeof dramas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDramas<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]短剧列表
 */

export function useDramas<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDramasQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getDramasSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDramasQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dramas>>> = ({
    signal,
  }) => dramas(userId, params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof dramas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DramasSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof dramas>>
>;
export type DramasSuspenseQueryError = ResultObject;

export function useDramasSuspense<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | DramasParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDramasSuspense<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDramasSuspense<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]短剧列表
 */

export function useDramasSuspense<
  TData = Awaited<ReturnType<typeof dramas>>,
  TError = ResultObject,
>(
  userId: number,
  params?: DramasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof dramas>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDramasSuspenseQueryOptions(userId, params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type actorCollectionsResponse200 = {
  data: PageDtoActorCollectionResponse;
  status: 200;
};

export type actorCollectionsResponse400 = {
  data: ResultObject;
  status: 400;
};

export type actorCollectionsResponseSuccess = actorCollectionsResponse200 & {
  headers: Headers;
};
export type actorCollectionsResponseError = actorCollectionsResponse400 & {
  headers: Headers;
};

export type actorCollectionsResponse =
  | actorCollectionsResponseSuccess
  | actorCollectionsResponseError;

export const getActorCollectionsUrl = (
  userId: number,
  params?: ActorCollectionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/user/profiles/${userId}/actor-collections?${stringifiedParams}`
    : `/api/mini-drama/user/profiles/${userId}/actor-collections`;
};

/**
 * @summary [鉴权]演员合集列表
 */
export const actorCollections = async (
  userId: number,
  params?: ActorCollectionsParams,
  options?: RequestInit,
): Promise<actorCollectionsResponse> => {
  return appAxiosInstance<actorCollectionsResponse>(
    getActorCollectionsUrl(userId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getActorCollectionsQueryKey = (
  userId: number,
  params?: ActorCollectionsParams,
) => {
  return [
    `/api/mini-drama/user/profiles/${userId}/actor-collections`,
    ...(params ? [params] : []),
  ] as const;
};

export const getActorCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getActorCollectionsQueryKey(userId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof actorCollections>>
  > = ({ signal }) =>
    actorCollections(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof actorCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ActorCollectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof actorCollections>>
>;
export type ActorCollectionsQueryError = ResultObject;

export function useActorCollections<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | ActorCollectionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof actorCollections>>,
          TError,
          Awaited<ReturnType<typeof actorCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useActorCollections<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof actorCollections>>,
          TError,
          Awaited<ReturnType<typeof actorCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useActorCollections<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]演员合集列表
 */

export function useActorCollections<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getActorCollectionsQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getActorCollectionsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getActorCollectionsQueryKey(userId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof actorCollections>>
  > = ({ signal }) =>
    actorCollections(userId, params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof actorCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ActorCollectionsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof actorCollections>>
>;
export type ActorCollectionsSuspenseQueryError = ResultObject;

export function useActorCollectionsSuspense<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params: undefined | ActorCollectionsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useActorCollectionsSuspense<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useActorCollectionsSuspense<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [鉴权]演员合集列表
 */

export function useActorCollectionsSuspense<
  TData = Awaited<ReturnType<typeof actorCollections>>,
  TError = ResultObject,
>(
  userId: number,
  params?: ActorCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof actorCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getActorCollectionsSuspenseQueryOptions(
    userId,
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
