/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * 派遣状态
 */
export type ActorLevelUpgradeMaterialResponseDeploymentStatus =
  (typeof ActorLevelUpgradeMaterialResponseDeploymentStatus)[keyof typeof ActorLevelUpgradeMaterialResponseDeploymentStatus];

export const ActorLevelUpgradeMaterialResponseDeploymentStatus = {
  MINING: 'MINING',
  REST: 'REST',
} as const;
