/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * 演员 NFT 咖位升级可用耗材数量
 */
export interface ActorLevelUpgradeMaterialCountResponse {
  /** 主材演员NFT ID，对应 mining_actor_nft.actor_nft_id */
  actorId?: string;
  /** 可用耗材数量 */
  count?: number;
}
