/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

export type ListRestActorsParams = {
  /**
   * 页码
   * @minimum 1
   */
  pageNum?: string;
  /**
   * 每页条数
   * @minimum 1
   * @maximum 100
   */
  pageSize?: string;
};
