/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * memo
 */
export interface Memo {
  /** Initial price multiplier */
  p0?: number;
  /** heat */
  heat?: number;
  /** actor IP trust */
  trust1?: number;
  /** user trust */
  trust2?: number;
  /** CP */
  CP?: number;
  /** Mining Coefficient */
  MC?: number;
}
