/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * 补充体力请求参数
 */
export interface ReplenishStaminaRequest {
  /** 演员 NFT ID */
  actorNftId: string;
  /**
   * 客户端确认的支付金额，单位为支付资产主单位。后端会按咖位规则重新计算并校验一致
   * @exclusiveMinimum 0
   */
  payAmount: number;
  /** 链上支付钱包地址。为空时使用用户绑定的 Solana 钱包 */
  walletAddress?: string;
}
