/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */
import type { ReplenishStaminaBatchItem } from './replenishStaminaBatchItem';

/**
 * 批量补充体力请求参数
 */
export interface ReplenishStaminaBatchRequest {
  /** 需要批量补充体力的演员列表。为空或不传时，按当前用户名下所有可补体力（挖矿中、体力未满、未消耗）的演员处理 */
  items?: ReplenishStaminaBatchItem[];
  /** 链上支付钱包地址。为空时使用用户绑定的 Solana 钱包 */
  walletAddress?: string;
}
