/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * 休息请求参数
 */
export interface RestActorRequest {
  /** 演员NFT链上ID */
  actorNftId: string;
}
