/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * 更改奖励列表
 */
export interface Reward {
  /** 记录ID */
  id: number;
  /** 新奖励值 */
  reward: number;
  /**
   * 备注
   * @minLength 0
   * @maxLength 100
   */
  memo?: string;
}
