/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * PENDING/APPROVED/REJECTED
 */
export type RewardDetailDTOAuditStatus =
  (typeof RewardDetailDTOAuditStatus)[keyof typeof RewardDetailDTOAuditStatus];

export const RewardDetailDTOAuditStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
