/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * 升级需求
 */
export interface UpgradeRequirement {
  /** 升级目标等级 */
  toLevel?: number;
  /** 所需材料数量 */
  requiredMaterialCount?: number;
  /** 升级费用 */
  fee?: number;
}
