/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Mining API
 * 挖矿服务接口
 * OpenAPI spec version: v1.0
 */

/**
 * 周期审核请求
 */
export interface WeekAuditRequest {
  /**
   * 周期N
   * @minimum 0
   * @maximum 1000
   */
  weekN: number;
  /**
   * 审核人
   * @minLength 0
   * @maxLength 64
   */
  auditBy?: string;
  /**
   * 审核备注
   * @minLength 0
   * @maxLength 500
   */
  auditRemark?: string;
}
