/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * 默认模块
 * 钱包服务 HTTP 接口 OpenAPI 文档。
 * 覆盖登录注册验签、邀请关系、用户资产、平台资产、充值、提现相关接口。
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type SuccessResponseMeta = { [key: string]: unknown } | null;
