/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  DramaPlayResponse,
  ListPublicShortVideosParams,
  PageDtoShortVideoListItemResponse,
  ResultObject,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listPublicShortVideosResponse200 = {
  data: PageDtoShortVideoListItemResponse;
  status: 200;
};

export type listPublicShortVideosResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listPublicShortVideosResponseSuccess =
  listPublicShortVideosResponse200 & {
    headers: Headers;
  };
export type listPublicShortVideosResponseError =
  listPublicShortVideosResponse400 & {
    headers: Headers;
  };

export type listPublicShortVideosResponse =
  | listPublicShortVideosResponseSuccess
  | listPublicShortVideosResponseError;

export const getListPublicShortVideosUrl = (
  params?: ListPublicShortVideosParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/public/short-videos?${stringifiedParams}`
    : `/api/mini-drama/public/short-videos`;
};

/**
 * @summary [无鉴权]短视频列表
 */
export const listPublicShortVideos = async (
  params?: ListPublicShortVideosParams,
  options?: RequestInit,
): Promise<listPublicShortVideosResponse> => {
  return appAxiosInstance<listPublicShortVideosResponse>(
    getListPublicShortVideosUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getListPublicShortVideosQueryKey = (
  params?: ListPublicShortVideosParams,
) => {
  return [
    `/api/mini-drama/public/short-videos`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListPublicShortVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListPublicShortVideosQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPublicShortVideos>>
  > = ({ signal }) =>
    listPublicShortVideos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPublicShortVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPublicShortVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPublicShortVideos>>
>;
export type ListPublicShortVideosQueryError = ResultObject;

export function useListPublicShortVideos<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params: undefined | ListPublicShortVideosParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicShortVideos>>,
          TError,
          Awaited<ReturnType<typeof listPublicShortVideos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicShortVideos<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicShortVideos>>,
          TError,
          Awaited<ReturnType<typeof listPublicShortVideos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicShortVideos<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]短视频列表
 */

export function useListPublicShortVideos<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPublicShortVideosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListPublicShortVideosSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListPublicShortVideosQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPublicShortVideos>>
  > = ({ signal }) =>
    listPublicShortVideos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listPublicShortVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPublicShortVideosSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPublicShortVideos>>
>;
export type ListPublicShortVideosSuspenseQueryError = ResultObject;

export function useListPublicShortVideosSuspense<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params: undefined | ListPublicShortVideosParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicShortVideosSuspense<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicShortVideosSuspense<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]短视频列表
 */

export function useListPublicShortVideosSuspense<
  TData = Awaited<ReturnType<typeof listPublicShortVideos>>,
  TError = ResultObject,
>(
  params?: ListPublicShortVideosParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicShortVideos>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPublicShortVideosSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getShortVideoDetailResponse200 = {
  data: DramaPlayResponse;
  status: 200;
};

export type getShortVideoDetailResponse400 = {
  data: ResultObject;
  status: 400;
};

export type getShortVideoDetailResponseSuccess =
  getShortVideoDetailResponse200 & {
    headers: Headers;
  };
export type getShortVideoDetailResponseError =
  getShortVideoDetailResponse400 & {
    headers: Headers;
  };

export type getShortVideoDetailResponse =
  | getShortVideoDetailResponseSuccess
  | getShortVideoDetailResponseError;

export const getGetShortVideoDetailUrl = (episodeId: number) => {
  return `/api/mini-drama/public/short-videos/${episodeId}`;
};

/**
 * @summary [无鉴权]短视频详情
 */
export const getShortVideoDetail = async (
  episodeId: number,
  options?: RequestInit,
): Promise<getShortVideoDetailResponse> => {
  return appAxiosInstance<getShortVideoDetailResponse>(
    getGetShortVideoDetailUrl(episodeId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetShortVideoDetailQueryKey = (episodeId: number) => {
  return [`/api/mini-drama/public/short-videos/${episodeId}`] as const;
};

export const getGetShortVideoDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetShortVideoDetailQueryKey(episodeId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getShortVideoDetail>>
  > = ({ signal }) =>
    getShortVideoDetail(episodeId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: episodeId !== null && episodeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getShortVideoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetShortVideoDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getShortVideoDetail>>
>;
export type GetShortVideoDetailQueryError = ResultObject;

export function useGetShortVideoDetail<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShortVideoDetail>>,
          TError,
          Awaited<ReturnType<typeof getShortVideoDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShortVideoDetail<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShortVideoDetail>>,
          TError,
          Awaited<ReturnType<typeof getShortVideoDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShortVideoDetail<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]短视频详情
 */

export function useGetShortVideoDetail<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetShortVideoDetailQueryOptions(episodeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetShortVideoDetailSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetShortVideoDetailQueryKey(episodeId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getShortVideoDetail>>
  > = ({ signal }) =>
    getShortVideoDetail(episodeId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getShortVideoDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetShortVideoDetailSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getShortVideoDetail>>
>;
export type GetShortVideoDetailSuspenseQueryError = ResultObject;

export function useGetShortVideoDetailSuspense<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShortVideoDetailSuspense<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetShortVideoDetailSuspense<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]短视频详情
 */

export function useGetShortVideoDetailSuspense<
  TData = Awaited<ReturnType<typeof getShortVideoDetail>>,
  TError = ResultObject,
>(
  episodeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getShortVideoDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetShortVideoDetailSuspenseQueryOptions(
    episodeId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
