/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ListParams,
  NotificationDeleteRequest,
  NotificationReadRequest,
  ResultBoolean,
  ResultCursorPageResponseNotificationItemResponse,
  ResultNotificationUnreadCountResponse,
  ResultObject,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type readResponse200 = {
  data: ResultBoolean;
  status: 200;
};

export type readResponse400 = {
  data: ResultObject;
  status: 400;
};

export type readResponse405 = {
  data: ResultObject;
  status: 405;
};

export type readResponse500 = {
  data: ResultObject;
  status: 500;
};

export type readResponseSuccess = readResponse200 & {
  headers: Headers;
};
export type readResponseError = (
  | readResponse400
  | readResponse405
  | readResponse500
) & {
  headers: Headers;
};

export type readResponse = readResponseSuccess | readResponseError;

export const getReadUrl = () => {
  return `/api/userWallet/notification/read`;
};

/**
 * 按 Tab 批量标记，或按通知 ID 列表精确标记；两种方式至少填写一种，操作幂等。
 * @summary 标记通知已读
 */
export const read = async (
  notificationReadRequest: NotificationReadRequest,
  options?: RequestInit,
): Promise<readResponse> => {
  return appAxiosInstance<readResponse>(getReadUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(notificationReadRequest),
  });
};

export const getReadMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof read>>,
    TError,
    { data: NotificationReadRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof read>>,
  TError,
  { data: NotificationReadRequest },
  TContext
> => {
  const mutationKey = ['read'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof read>>,
    { data: NotificationReadRequest }
  > = (props) => {
    const { data } = props ?? {};

    return read(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReadMutationResult = NonNullable<Awaited<ReturnType<typeof read>>>;
export type ReadMutationBody = NotificationReadRequest;
export type ReadMutationError = ResultObject;

/**
 * @summary 标记通知已读
 */
export const useRead = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof read>>,
      TError,
      { data: NotificationReadRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof read>>,
  TError,
  { data: NotificationReadRequest },
  TContext
> => {
  return useMutation(getReadMutationOptions(options), queryClient);
};
export type _deleteResponse200 = {
  data: ResultBoolean;
  status: 200;
};

export type _deleteResponse400 = {
  data: ResultObject;
  status: 400;
};

export type _deleteResponse405 = {
  data: ResultObject;
  status: 405;
};

export type _deleteResponse500 = {
  data: ResultObject;
  status: 500;
};

export type _deleteResponseSuccess = _deleteResponse200 & {
  headers: Headers;
};
export type _deleteResponseError = (
  | _deleteResponse400
  | _deleteResponse405
  | _deleteResponse500
) & {
  headers: Headers;
};

export type _deleteResponse = _deleteResponseSuccess | _deleteResponseError;

export const getDeleteUrl = () => {
  return `/api/userWallet/notification/delete`;
};

/**
 * 逻辑删除当前登录用户的一条通知；不能删除其他用户的通知。
 * @summary 删除通知
 */
export const _delete = async (
  notificationDeleteRequest: NotificationDeleteRequest,
  options?: RequestInit,
): Promise<_deleteResponse> => {
  return appAxiosInstance<_deleteResponse>(getDeleteUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(notificationDeleteRequest),
  });
};

export const getDeleteMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof _delete>>,
    TError,
    { data: NotificationDeleteRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { data: NotificationDeleteRequest },
  TContext
> => {
  const mutationKey = ['_delete'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof _delete>>,
    { data: NotificationDeleteRequest }
  > = (props) => {
    const { data } = props ?? {};

    return _delete(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type _DeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof _delete>>
>;
export type _DeleteMutationBody = NotificationDeleteRequest;
export type _DeleteMutationError = ResultObject;

/**
 * @summary 删除通知
 */
export const useDelete = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof _delete>>,
      TError,
      { data: NotificationDeleteRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { data: NotificationDeleteRequest },
  TContext
> => {
  return useMutation(getDeleteMutationOptions(options), queryClient);
};
export type unreadCountResponse200 = {
  data: ResultNotificationUnreadCountResponse;
  status: 200;
};

export type unreadCountResponse400 = {
  data: ResultObject;
  status: 400;
};

export type unreadCountResponse405 = {
  data: ResultObject;
  status: 405;
};

export type unreadCountResponse500 = {
  data: ResultObject;
  status: 500;
};

export type unreadCountResponseSuccess = unreadCountResponse200 & {
  headers: Headers;
};
export type unreadCountResponseError = (
  | unreadCountResponse400
  | unreadCountResponse405
  | unreadCountResponse500
) & {
  headers: Headers;
};

export type unreadCountResponse =
  | unreadCountResponseSuccess
  | unreadCountResponseError;

export const getUnreadCountUrl = () => {
  return `/api/userWallet/notification/unreadCount`;
};

/**
 * 返回收益 Tab、互动 Tab 以及全部通知的未读数量，数量字段均为字符串。
 * @summary 查询通知未读计数
 */
export const unreadCount = async (
  options?: RequestInit,
): Promise<unreadCountResponse> => {
  return appAxiosInstance<unreadCountResponse>(getUnreadCountUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getUnreadCountQueryKey = () => {
  return [`/api/userWallet/notification/unreadCount`] as const;
};

export const getUnreadCountQueryOptions = <
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof unreadCount>>, TError, TData>
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUnreadCountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof unreadCount>>> = ({
    signal,
  }) => unreadCount({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof unreadCount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UnreadCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof unreadCount>>
>;
export type UnreadCountQueryError = ResultObject;

export function useUnreadCount<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unreadCount>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof unreadCount>>,
          TError,
          Awaited<ReturnType<typeof unreadCount>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnreadCount<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unreadCount>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof unreadCount>>,
          TError,
          Awaited<ReturnType<typeof unreadCount>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnreadCount<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unreadCount>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询通知未读计数
 */

export function useUnreadCount<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unreadCount>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUnreadCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getUnreadCountSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof unreadCount>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUnreadCountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof unreadCount>>> = ({
    signal,
  }) => unreadCount({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof unreadCount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UnreadCountSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof unreadCount>>
>;
export type UnreadCountSuspenseQueryError = ResultObject;

export function useUnreadCountSuspense<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof unreadCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnreadCountSuspense<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof unreadCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnreadCountSuspense<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof unreadCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询通知未读计数
 */

export function useUnreadCountSuspense<
  TData = Awaited<ReturnType<typeof unreadCount>>,
  TError = ResultObject,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof unreadCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUnreadCountSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type listResponse200 = {
  data: ResultCursorPageResponseNotificationItemResponse;
  status: 200;
};

export type listResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listResponse405 = {
  data: ResultObject;
  status: 405;
};

export type listResponse500 = {
  data: ResultObject;
  status: 500;
};

export type listResponseSuccess = listResponse200 & {
  headers: Headers;
};
export type listResponseError = (
  | listResponse400
  | listResponse405
  | listResponse500
) & {
  headers: Headers;
};

export type listResponse = listResponseSuccess | listResponseError;

export const getListUrl = (params?: ListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/userWallet/notification/list?${stringifiedParams}`
    : `/api/userWallet/notification/list`;
};

/**
 * 查询当前登录用户的通知列表，可按 Tab 和 eventType 筛选，使用通知 ID 倒序游标分页。
 * 每条通知的 data 都包含字符串形式的 behaviorId（来源行为/业务记录 ID）和 objectId（目标对象 ID）。
 * LIKE、FAVORITE、COMMENT 根据 targetType(video/drama) + objectId 动态补充 targetName、coverUrl；
 * IP_SIGN、STAMINA_LOW 根据 objectId（角色 IP ID）动态补充 ipName、ipAvatarUrl。
 * @summary 分页查询站内通知
 */
export const list = async (
  params?: ListParams,
  options?: RequestInit,
): Promise<listResponse> => {
  return appAxiosInstance<listResponse>(getListUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getListQueryKey = (params?: ListParams) => {
  return [
    `/api/userWallet/notification/list`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListQueryOptions = <
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list>>> = ({
    signal,
  }) => list(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof list>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQueryResult = NonNullable<Awaited<ReturnType<typeof list>>>;
export type ListQueryError = ResultObject;

export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params: undefined | ListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 分页查询站内通知
 */

export function useList<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list>>> = ({
    signal,
  }) => list(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof list>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof list>>
>;
export type ListSuspenseQueryError = ResultObject;

export function useListSuspense<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params: undefined | ListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuspense<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuspense<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 分页查询站内通知
 */

export function useListSuspense<
  TData = Awaited<ReturnType<typeof list>>,
  TError = ResultObject,
>(
  params?: ListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
