/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { NftInfo } from './nftInfo';

export interface ActorCollectionInfo {
  id?: number;
  name?: string;
  avatar?: string;
  nft?: NftInfo;
  computingPower?: number;
}
