/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type ActorCollectionResponseBadge =
  (typeof ActorCollectionResponseBadge)[keyof typeof ActorCollectionResponseBadge];

export const ActorCollectionResponseBadge = {
  OFFICIAL: 'OFFICIAL',
  PARTNER: 'PARTNER',
  VERIFIED: 'VERIFIED',
  COMMUNITY: 'COMMUNITY',
} as const;
