/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { AdminCommentItemResponseAuditStatus } from './adminCommentItemResponseAuditStatus';
import type { AdminCommentItemResponseItemType } from './adminCommentItemResponseItemType';
import type { AdminCommentItemResponseLevel } from './adminCommentItemResponseLevel';

/**
 * 运营后台评论列表项
 */
export interface AdminCommentItemResponse {
  /** 评论 ID */
  commentId?: number;
  /** 评论正文 */
  content?: string;
  /** 层级 */
  level?: AdminCommentItemResponseLevel;
  /** 根评论 ID；一级评论为 null */
  rootId?: number;
  /** 直接父评论 ID */
  parentId?: number;
  /** 作品类型 */
  itemType?: AdminCommentItemResponseItemType;
  /** 被回复人用户 ID（UID） */
  replyToUserId?: number;
  /** 被回复人昵称 */
  replyToNickname?: string;
  /** 关联作品 ID（短剧为分集 ID） */
  workId?: number;
  /** 分集标题 */
  workTitle?: string;
  /** 短剧 ID */
  dramaId?: number;
  /** 短剧标题 */
  dramaTitle?: string;
  /** 分集序号，从 1 开始 */
  episodeNo?: number;
  /** 视频预览地址（优先 HLS） */
  previewUrl?: string;
  /** 评论人用户 ID（UID） */
  userId?: number;
  /** 评论人昵称 */
  nickname?: string;
  /** 点赞数 */
  likeCount?: number;
  /** 二级回复数，仅根评论返回 */
  replyCount?: number;
  /** 审核状态 */
  auditStatus?: AdminCommentItemResponseAuditStatus;
  /** 是否已删除（deleted_at 非空） */
  deleted?: boolean;
  /** 删除时间（毫秒时间戳） */
  deletedAt?: number;
  /** 删除原因 */
  deletedReason?: string;
  /** 创建时间（毫秒时间戳） */
  createdAt?: number;
}
