/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 审核状态
 */
export type AdminCommentItemResponseAuditStatus =
  (typeof AdminCommentItemResponseAuditStatus)[keyof typeof AdminCommentItemResponseAuditStatus];

export const AdminCommentItemResponseAuditStatus = {
  APPROVED: 'APPROVED',
  PENDING: 'PENDING',
} as const;
