/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 层级
 */
export type AdminCommentItemResponseLevel =
  (typeof AdminCommentItemResponseLevel)[keyof typeof AdminCommentItemResponseLevel];

export const AdminCommentItemResponseLevel = {
  ROOT: 'ROOT',
  REPLY: 'REPLY',
} as const;
