/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 作品类型
 */
export type AdminCommentItemResponseItemType =
  (typeof AdminCommentItemResponseItemType)[keyof typeof AdminCommentItemResponseItemType];

export const AdminCommentItemResponseItemType = {
  EPISODE: 'EPISODE',
  SHORT_VIDEO: 'SHORT_VIDEO',
} as const;
