/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type ClearParams = {
  /**
   * 清空范围：ALL / DRAMA / VIDEO
   */
  scope?: string;
};
