/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 数据列表
 */
export interface CollectionListItemResponse {
  collectionId?: number;
  title?: string;
  description?: string;
  coverUrl?: string;
  status?: string;
  episodeCount?: number;
  createdAt?: number;
}
