/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 展示标签
 */
export type CommentResponseTagsItem =
  (typeof CommentResponseTagsItem)[keyof typeof CommentResponseTagsItem];

export const CommentResponseTagsItem = {
  AUTHOR: 'AUTHOR',
  ME: 'ME',
  FRIEND: 'FRIEND',
  FAN: 'FAN',
  FIRST: 'FIRST',
  AUTHOR_LIKED: 'AUTHOR_LIKED',
} as const;
