/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 评论操作审计日志
 */
export interface CommentAuditLogResponse {
  /** 日志 ID */
  logId?: number;
  /**
   * 后管操作人用户 ID（字符串，非 C 端 UID）
   * @maxLength 64
   */
  operatorId?: string;
  /** 操作类型，当前主要为 DELETE */
  action?: string;
  /** 操作原因 */
  reason?: string;
  /** 操作时间（毫秒时间戳） */
  createdAt?: number;
}
