/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface CreateCollectionRequest {
  uploadSessionId: number;
  /**
   * @minLength 0
   * @maxLength 256
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description?: string;
  coverObjectKey: string;
}
