/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { BatchEpisodeItem } from './batchEpisodeItem';

export interface CreateDramaRequest {
  uploadSessionId: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description: string;
  coverObjectKey: string;
  episodes: BatchEpisodeItem[];
  /**
   * 角色 IP 绑定（可选），最多 5 个。每个必须是用户持有且已铸造上线的角色 IP 合集 ID。Clients should send this as a string array to avoid JavaScript number precision loss.
   * @minItems 0
   * @maxItems 5
   */
  actorCollectionIds?: number[];
  /** Tag IDs. Clients should send this as a string array to avoid JavaScript number precision loss, for example ["9007199254740993", "2"]. */
  tagIds: number[];
}
