/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface DramaEditContextEpisodeResponse {
  id?: number;
  episodeNo?: number;
  title?: string;
  description?: string;
  videoUrl?: string;
  videoSizeBytes?: number;
  durationSec?: number;
  width?: number;
  height?: number;
  hlsOutputKey?: string;
  hlsUrl?: string;
}
