/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type DramaDetailResponseBadge =
  (typeof DramaDetailResponseBadge)[keyof typeof DramaDetailResponseBadge];

export const DramaDetailResponseBadge = {
  OFFICIAL: 'OFFICIAL',
  PARTNER: 'PARTNER',
  VERIFIED: 'VERIFIED',
  COMMUNITY: 'COMMUNITY',
} as const;
