/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type DramaListItemResponseBadge =
  (typeof DramaListItemResponseBadge)[keyof typeof DramaListItemResponseBadge];

export const DramaListItemResponseBadge = {
  OFFICIAL: 'OFFICIAL',
  PARTNER: 'PARTNER',
  VERIFIED: 'VERIFIED',
  COMMUNITY: 'COMMUNITY',
} as const;
