/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { ActorCollectionInfo } from './actorCollectionInfo';
import type { DramaInfo } from './dramaInfo';

export interface DramaDetailInfoResponse {
  dramaInfo?: DramaInfo;
  actorCollections?: ActorCollectionInfo[];
  totalEpisodes?: number;
}
