/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface DramaNftMintDigestResponse {
  userId?: number;
  dramaId?: number;
  creatorAddress?: string;
  mintWalletAddress?: string;
  nftChain?: string;
  nftTokenStandard?: string;
  nftContractAddress?: string;
  metadataUrl?: string;
  payToken?: string;
  feeAmount?: string;
  issuedAt?: number;
  expiresAt?: number;
  canonicalPayload?: string;
  sig?: string;
}
