/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { ActorCollectionInfoResponse } from './actorCollectionInfoResponse';
import type { DramaInfoBadge } from './dramaInfoBadge';

/**
 * Drama-level detail
 */
export interface DramaInfo {
  /** Drama ID */
  dramaId?: number;
  /** Drama title */
  title?: string;
  /** Drama description */
  description?: string;
  /** Drama cover image URL */
  coverUrl?: string;
  /** Drama status, e.g. ONLINE / OFFLINE / PENDING_REVIEW / REVIEW_REJECTED / DELETED */
  status?: string;
  /** Content type from DB, e.g. SHORT_DRAMA */
  contentType?: string;
  /** Localized tag names */
  tags?: string[];
  /** Total episode count */
  totalEpisodes?: number;
  /** Badge label */
  badge?: DramaInfoBadge;
  /** Bound actor collections */
  actorCollections?: ActorCollectionInfoResponse[];
  /** Total play count across all episodes */
  totalPlayCount?: number;
  /** Total completed-view count across all episodes */
  totalCompletedViewCount?: number;
  /** Total favorite count */
  totalFavoriteCount?: number;
  /** Aggregated heat value */
  totalHeatValue?: number;
  /** Average rating score */
  avgRating?: number;
}
