/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * Episode-level detail
 */
export interface EpisodeInfo {
  /** Episode ID */
  episodeId?: number;
  /** Episode number within the drama (null for standalone short video) */
  episodeNo?: number;
  /** Content type from DB, e.g. SHORT_DRAMA / SHORT_VIDEO */
  contentType?: string;
  /** Episode status, e.g. ONLINE / OFFLINE / PENDING_REVIEW / REVIEW_REJECTED / DELETED */
  status?: string;
  /** Duration in seconds */
  durationSec?: number;
  /** Episode title (backfilled from drama if null) */
  title?: string;
  /** Episode description (backfilled from drama if null) */
  description?: string;
  /** Episode cover URL (backfilled from drama if null) */
  coverUrl?: string;
  /** Play count */
  playCount?: number;
  /** Completed-view count */
  completeCount?: number;
  /** Like count */
  likeCount?: number;
  /** Comment count */
  commentCount?: number;
  /** Favorite count */
  favoriteCount?: number;
  /** HLS playback URL (m3u8), null if not transcoded */
  mediaAccessUrl?: string;
  /** Media playback type, e.g. HLS */
  playbackType?: string;
  /** Original video URL (before transcoding) */
  videoUrl?: string;
}
