/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { ListReportTypesScope } from './listReportTypesScope';

export type ListReportTypesParams = {
  /**
   * 适用对象，不传返回全部
   */
  scope?: ListReportTypesScope;
};
