/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type ListRootCommentsParams = {
  /**
   * 热度复合游标 sortScore_id，首页不传；末页 mark 为 -1
   */
  mark?: string;
  /**
   * 每页条数，默认 20，范围 1~100
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
};
