/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type ListRecentParams = {
  /**
   * 返回条数，默认 3，最大 10
   * @minimum 1
   * @maximum 10
   */
  limit?: number;
};
