/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type ListVideosParams = {
  /**
   * 分页游标，格式 lastWatchedAt_id；首页不传
   */
  mark?: string;
  /**
   * 每页条数，默认 20，最大 100
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
};
