/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { ListPublicDramasSort } from './listPublicDramasSort';

export type ListPublicDramasParams = {
  mark?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
  tags?: string;
  tagId?: number;
  sort?: ListPublicDramasSort;
};
