/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export type ListAddableEpisodesParams = {
  /**
   * @minimum -1
   */
  mark?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
};
