/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface PostReviewRequest {
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /**
   * @minLength 0
   * @maxLength 500
   */
  reviewText?: string;
}
