/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface PrepareActorCollectionResponse {
  actorCollectionId?: number;
  assetId?: string;
  name?: string;
  avatarUrl?: string;
  bio?: string;
  totalSupply?: number;
  initialPriceUsdc?: number;
  trust?: number;
  pricingMode?: string;
  status?: string;
  expiresAt?: number;
}
