/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface RecommendEpisodeIdsRequest {
  /**
   * 剧集ID列表，最多50个
   * @minItems 0
   * @maxItems 50
   */
  episodeIds: number[];
  /** 用户ID，可选。传入时回显该用户对每个剧集的点赞(likedByMe)/收藏(favoritedByMe)状态；不传视为未登录用户，不做回显查询 */
  userId?: number;
  /** Tag i18n language, defaults to "en". Used to localize tag names in the response. */
  language?: string;
}
