/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 批量上报观看历史响应
 */
export interface ReportWatchHistoryResponse {
  /** 成功接收的条数（合并重复 episodeId 后） */
  accepted?: number;
}
