/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { ResultVoidData } from './resultVoidData';

export interface ResultVoid {
  msg?: string;
  code?: number;
  data?: ResultVoidData;
}
