/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { ReviewResponse } from './reviewResponse';

export interface ResultReviewResponse {
  msg?: string;
  code?: number;
  data?: ReviewResponse;
}
