/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 输出方向：LANDSCAPE（横屏，默认）/ PORTRAIT（竖屏）
 */
export type ReTranscodeEpisodesRequestOrientation =
  (typeof ReTranscodeEpisodesRequestOrientation)[keyof typeof ReTranscodeEpisodesRequestOrientation];

export const ReTranscodeEpisodesRequestOrientation = {
  LANDSCAPE: 'LANDSCAPE',
  PORTRAIT: 'PORTRAIT',
} as const;
