/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface ReviewResponse {
  id?: number;
  userId?: number;
  dramaId?: number;
  rating?: number;
  reviewText?: string;
  createdAt?: number;
  updatedAt?: number;
}
