/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface ReviewDecisionRequest {
  approved?: boolean;
  /**
   * @minLength 0
   * @maxLength 200
   */
  auditReason?: string;
}
