/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface ShortVideoListItemResponse {
  episodeId?: number;
  userId?: number;
  collectionId?: number;
  title?: string;
  description?: string;
  coverUrl?: string;
  videoUrl?: string;
  status?: string;
  durationSec?: number;
  playCount?: number;
  likeCount?: number;
  commentCount?: number;
  auditReason?: string;
  createdAt?: number;
}
