/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 提交 UGC 举报请求
 */
export interface SubmitUgcReportRequest {
  /** 举报原因编码，对应 report_type.code；可先调 GET /api/mini-drama/public/ugc/report-types 获取 */
  reportType: string;
  /**
   * 补充说明，可选；trim 后为空则忽略，最多 500 字符
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
}
