/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { BatchEpisodeItem } from './batchEpisodeItem';

export interface SyncDramaFromDreamOsRequest {
  uploadSessionId: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description: string;
  coverObjectKey: string;
  episodes: BatchEpisodeItem[];
  /**
   * 角色 IP 绑定（可选），最多 5 个。每个必须是用户持有且已铸造上线的角色 IP 合集 ID。
   * @minItems 0
   * @maxItems 5
   */
  actorCollectionIds?: number[];
  /** Tag IDs. If empty, DreamOS default tag will be used. */
  tagIds?: number[];
}
