/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { UgcReportDetailLinkResponse } from './ugcReportDetailLinkResponse';
import type { UgcReportReasonCountResponse } from './ugcReportReasonCountResponse';

/**
 * 评论举报工单
 */
export interface UgcCommentReportTicketResponse {
  /** 工单 ID */
  ticketId?: number;
  /** 评论 ID */
  commentId?: number;
  /** 被举报评论原文 */
  content?: string;
  /** 评论发布者 UID */
  authorUserId?: number;
  /** 评论发布者昵称 */
  authorNickname?: string;
  /** 所属作品 ID（episodeId） */
  episodeId?: number;
  /** 所属作品标题 */
  workTitle?: string;
  /** 作品类型 EPISODE / SHORT_VIDEO */
  itemType?: string;
  /** 原因汇总，中文名 */
  reasonSummary?: UgcReportReasonCountResponse[];
  /** 首次举报时间（毫秒） */
  firstReportedAt?: number;
  /** 最新举报时间（毫秒） */
  lastReportedAt?: number;
  /** 累计举报次数 */
  reportCount?: number;
  detailLink?: UgcReportDetailLinkResponse;
}
