/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 先发后审跳转参数
 */
export interface UgcReportDetailLinkResponse {
  /** 对象类型 SHORT_VIDEO / DRAMA_EPISODE / DRAMA / COMMENT */
  targetType?: string;
  /** 跳转主键：作品为 episodeId，短剧为 dramaId，评论为 commentId */
  targetId?: number;
  /** 短剧 ID，可空 */
  dramaId?: number;
  /** 作品 episode ID，可空 */
  episodeId?: number;
}
