/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 举报明细
 */
export interface UgcReportLogItemResponse {
  /** 明细 ID */
  logId?: number;
  /** 举报人 UID */
  reporterUserId?: number;
  /** 举报人昵称 */
  reporterNickname?: string;
  /** 原因编码 */
  reportTypeCode?: string;
  /** 原因中文名 */
  reportTypeName?: string;
  /** 补充描述 */
  description?: string;
  /** 提交时间（毫秒） */
  createdAt?: number;
}
