/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { UgcReportDetailLinkResponse } from './ugcReportDetailLinkResponse';
import type { UgcReportReasonCountResponse } from './ugcReportReasonCountResponse';

/**
 * 用户举报工单
 */
export interface UgcUserReportTicketResponse {
  /** 工单 ID */
  ticketId?: number;
  /** 被举报用户 ID */
  userId?: number;
  /** 被举报用户昵称 */
  nickname?: string;
  /** 被举报用户头像 */
  avatarUrl?: string;
  /** 原因汇总，中文名 */
  reasonSummary?: UgcReportReasonCountResponse[];
  /** 首次举报时间（毫秒） */
  firstReportedAt?: number;
  /** 最新举报时间（毫秒） */
  lastReportedAt?: number;
  /** 累计举报次数 */
  reportCount?: number;
  detailLink?: UgcReportDetailLinkResponse;
}
