/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { UgcReportDetailLinkResponse } from './ugcReportDetailLinkResponse';
import type { UgcReportReasonCountResponse } from './ugcReportReasonCountResponse';

/**
 * 作品举报工单
 */
export interface UgcWorkReportTicketResponse {
  /** 工单 ID */
  ticketId?: number;
  /** 作品 ID，即 drama_episode.id */
  episodeId?: number;
  /** 作品标题；单集为空时回退短剧标题 */
  title?: string;
  /** 封面 URL */
  coverUrl?: string;
  /** 预览地址，优先 HLS */
  previewUrl?: string;
  /** 作品子类型 SHORT_VIDEO / DRAMA_EPISODE */
  workKind?: string;
  /** 所属短剧 ID，短视频为空 */
  dramaId?: number;
  /** 所属短剧名称 */
  dramaTitle?: string;
  /** 集号，从 1 开始 */
  episodeNo?: number;
  /** 作者 UID */
  authorUserId?: number;
  /** 作者昵称 */
  authorNickname?: string;
  /** 原因汇总，中文名 */
  reasonSummary?: UgcReportReasonCountResponse[];
  /** 首次举报时间（毫秒） */
  firstReportedAt?: number;
  /** 最新举报时间（毫秒） */
  lastReportedAt?: number;
  /** 累计举报次数 */
  reportCount?: number;
  detailLink?: UgcReportDetailLinkResponse;
}
