/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

export interface UpdateShortVideoRequest {
  /** 封面重新上传时的上传会话,配合 coverObjectKey 使用 */
  uploadSessionId?: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  title?: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description?: string;
  /** 选填,替换封面时必填 */
  coverObjectKey?: string;
}
