/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { DramaInfo } from './dramaInfo';
import type { EpisodeInfo } from './episodeInfo';
import type { UserProfileUnifiedResponseType } from './userProfileUnifiedResponseType';

/**
 * Unified user profile item: common fields + drama and/or episode embedded objects
 */
export interface UserProfileUnifiedResponse {
  /** Drama creator user ID */
  userId?: number;
  /** Drama creator nickname */
  creatorName?: string;
  /** Drama creator avatar URL */
  creatorAvatarUrl?: string;
  /** Whether the current user has liked this episode (drama-dimension: always null; episode-dimension: true/false) */
  likedByMe?: boolean;
  /** Whether the current user has favorited this drama/episode */
  favoritedByMe?: boolean;
  /** Whether the current user is following the drama creator */
  followedByMe?: boolean;
  /** Action time. Published uses drama created time, favorites uses favorite time */
  actionTime?: number;
  /** Display type discriminator: DRAMA / DRAMA_EPISODE / SHORT_VIDEO */
  type?: UserProfileUnifiedResponseType;
  drama?: DramaInfo;
  episode?: EpisodeInfo;
}
