/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 认证角标
 */
export type WatchHistoryDramaItemResponseBadge =
  (typeof WatchHistoryDramaItemResponseBadge)[keyof typeof WatchHistoryDramaItemResponseBadge];

export const WatchHistoryDramaItemResponseBadge = {
  OFFICIAL: 'OFFICIAL',
  PARTNER: 'PARTNER',
  VERIFIED: 'VERIFIED',
  COMMUNITY: 'COMMUNITY',
} as const;
