/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */
import type { WatchHistoryDramaItemResponse } from './watchHistoryDramaItemResponse';
import type { WatchHistoryRecentItemResponseKind } from './watchHistoryRecentItemResponseKind';
import type { WatchHistoryVideoItemResponse } from './watchHistoryVideoItemResponse';

/**
 * 观看历史最近预览条目
 */
export interface WatchHistoryRecentItemResponse {
  /** 条目类型：DRAMA 短剧续看 / VIDEO 独立短视频 */
  kind?: WatchHistoryRecentItemResponseKind;
  /** 最近观看时间（毫秒），用于混排排序 */
  watchedAt?: number;
  drama?: WatchHistoryDramaItemResponse;
  video?: WatchHistoryVideoItemResponse;
}
