/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

/**
 * 视频观看历史列表项
 */
export interface WatchHistoryVideoItemResponse {
  /** 内容 ID（drama_episode.id） */
  episodeId?: number;
  /** 所属短剧 ID；独立短视频为空 */
  dramaId?: number;
  /** 分集号；有值时展示「第 N 集」标签 */
  episodeNo?: number;
  /** 内容类型：SHORT_DRAMA / SHORT_VIDEO */
  contentType?: string;
  /** 标题 */
  title?: string;
  /** 封面 URL */
  coverUrl?: string;
  /** 描述（PC 端展示） */
  description?: string;
  /** 点赞数 */
  likeCount?: number;
}
