/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Recommend API
 * StoryFun 推荐服务（首页「推荐」Tab）。
 * <p>
 * 主要接口：
 * <ul>
 *   <li><b>GET /api/recommend/feed</b> — 推荐流（支持未登录；首屏默认 10 条）</li>
 *   <li><b>GET /api/recommend/search</b> — 模糊搜索（支持未登录；keyword 必填，2~50 字）</li>
 *   <li><b>POST /api/recommend/dislike/{videoId}</b> — 不感兴趣（需登录；videoId = episodeId）</li>
 * </ul>
 * 标注「联调使用」的字段 / Debug 接口仅供联调排查。
 *
 * OpenAPI spec version: v0.5
 */
import type { ExplainResponseScoreBreakdown } from './explainResponseScoreBreakdown';

/**
 * 联调使用：打分解释
 */
export interface ExplainResponse {
  /** 联调使用 */
  userId?: string;
  /** 联调使用 */
  dramaId?: string;
  /** 联调使用：推荐单元 ID */
  episodeId?: string;
  /** 联调使用：最终分；base≥0 时为 base × actorBoost × authorBoost，负向兴趣时 base 可为负 */
  finalScore?: number;
  /** 联调使用：各因子原始分 */
  scoreBreakdown?: ExplainResponseScoreBreakdown;
  /** 联调使用：当前用户走的分支说明 */
  note?: string;
}
