/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Recommend API
 * StoryFun 推荐服务（首页「推荐」Tab）。
 * <p>
 * 主要接口：
 * <ul>
 *   <li><b>GET /api/recommend/feed</b> — 推荐流（支持未登录；首屏默认 10 条）</li>
 *   <li><b>GET /api/recommend/search</b> — 模糊搜索（支持未登录；keyword 必填，2~50 字）</li>
 *   <li><b>POST /api/recommend/dislike/{videoId}</b> — 不感兴趣（需登录；videoId = episodeId）</li>
 * </ul>
 * 标注「联调使用」的字段 / Debug 接口仅供联调排查。
 *
 * OpenAPI spec version: v0.5
 */

export * from './actorCollectionInfoResponse';
export * from './dramaInfo';
export * from './episodeInfo';
export * from './explainParams';
export * from './explainResponse';
export * from './explainResponseScoreBreakdown';
export * from './feedItemResponse';
export * from './feedItemResponseType';
export * from './feedParams';
export * from './feedResponse';
export * from './resultExplainResponse';
export * from './resultFeedResponse';
export * from './resultMapStringString';
export * from './resultMapStringStringData';
export * from './resultObject';
export * from './resultObjectData';
export * from './resultSearchResponse';
export * from './resultSnapshotDebugResponse';
export * from './resultVoid';
export * from './resultVoidData';
export * from './searchParams';
export * from './searchResponse';
export * from './searchResponseType';
export * from './searchType';
export * from './snapshotDebugResponse';
export * from './snapshotParams';
