/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Recommend API
 * StoryFun 推荐服务（首页「推荐」Tab）。
 * <p>
 * 主要接口：
 * <ul>
 *   <li><b>GET /api/recommend/feed</b> — 推荐流（支持未登录；首屏默认 10 条）</li>
 *   <li><b>GET /api/recommend/search</b> — 模糊搜索（支持未登录；keyword 必填，2~50 字）</li>
 *   <li><b>POST /api/recommend/dislike/{videoId}</b> — 不感兴趣（需登录；videoId = episodeId）</li>
 * </ul>
 * 标注「联调使用」的字段 / Debug 接口仅供联调排查。
 *
 * OpenAPI spec version: v0.5
 */
import type { FeedItemResponse } from './feedItemResponse';
import type { SearchResponseType } from './searchResponseType';

/**
 * 模糊搜索结果（items 同构 Feed 卡片；app 回源 + 索引补齐；无高亮；cursor 翻页）
 */
export interface SearchResponse {
  /** 原始关键词（已 trim） */
  keyword?: string;
  /** 类型：all=短剧集+短视频不折叠；drama/drama_episode=短剧首页集；short_video=短视频 */
  type?: SearchResponseType;
  /** 下一页 cursor，有更多时返回，原样回传即可续页 */
  cursor?: string;
  /** 是否还有更多 */
  hasMore?: boolean;
  /** 结果列表，字段同 Feed；登录时含 likedByMe / favoritedByMe / followedByMe */
  items?: FeedItemResponse[];
}
