/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Recommend API
 * StoryFun 推荐服务（首页「推荐」Tab）。
 * <p>
 * 主要接口：
 * <ul>
 *   <li><b>GET /api/recommend/feed</b> — 推荐流（支持未登录；首屏默认 10 条）</li>
 *   <li><b>GET /api/recommend/search</b> — 模糊搜索（支持未登录；keyword 必填，2~50 字）</li>
 *   <li><b>POST /api/recommend/dislike/{videoId}</b> — 不感兴趣（需登录；videoId = episodeId）</li>
 * </ul>
 * 标注「联调使用」的字段 / Debug 接口仅供联调排查。
 *
 * OpenAPI spec version: v0.5
 */
import type { FeedItemResponse } from './feedItemResponse';

/**
 * 联调使用：当前推荐快照详情
 */
export interface SnapshotDebugResponse {
  /** 联调使用 */
  userId?: string;
  /** 联调使用：缓存 key */
  cacheKey?: string;
  /** 联调使用 */
  sessionId?: string;
  /** 联调使用：生成时间戳（毫秒） */
  generatedAt?: number;
  /** 联调使用：尚未返回条数 */
  remaining?: number;
  /** 联调使用：快照内全部条目 */
  items?: FeedItemResponse[];
}
