/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama User Wallet API
 * 用户、钱包、任务中心接口
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ResultObject,
  WithdrawCreateResponse,
  WithdrawDetailResponse,
  WithdrawRequest,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type withdrawResponse200 = {
  data: ResultObject;
  status: 200;
};

export type withdrawResponse400 = {
  data: ResultObject;
  status: 400;
};

export type withdrawResponse401 = {
  data: WithdrawCreateResponse;
  status: 401;
};

export type withdrawResponse405 = {
  data: ResultObject;
  status: 405;
};

export type withdrawResponse500 = {
  data: ResultObject;
  status: 500;
};

export type withdrawResponseSuccess = withdrawResponse200 & {
  headers: Headers;
};
export type withdrawResponseError = (
  | withdrawResponse400
  | withdrawResponse401
  | withdrawResponse405
  | withdrawResponse500
) & {
  headers: Headers;
};

export type withdrawResponse = withdrawResponseSuccess | withdrawResponseError;

export const getWithdrawUrl = () => {
  return `/api/userWallet/withdraw`;
};

/**
 * 用户将中心化 STORY、USDC 余额提取到去中心化钱包；钱包冻结余额并调用 Node 服务打款。
 * @summary 发起提取
 */
export const withdraw = async (
  withdrawRequest: WithdrawRequest,
  options?: RequestInit,
): Promise<withdrawResponse> => {
  return appAxiosInstance<withdrawResponse>(getWithdrawUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(withdrawRequest),
  });
};

export const getWithdrawMutationOptions = <
  TError = ResultObject | WithdrawCreateResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof withdraw>>,
    TError,
    { data: WithdrawRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof withdraw>>,
  TError,
  { data: WithdrawRequest },
  TContext
> => {
  const mutationKey = ['withdraw'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof withdraw>>,
    { data: WithdrawRequest }
  > = (props) => {
    const { data } = props ?? {};

    return withdraw(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WithdrawMutationResult = NonNullable<
  Awaited<ReturnType<typeof withdraw>>
>;
export type WithdrawMutationBody = WithdrawRequest;
export type WithdrawMutationError = ResultObject | WithdrawCreateResponse;

/**
 * @summary 发起提取
 */
export const useWithdraw = <
  TError = ResultObject | WithdrawCreateResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof withdraw>>,
      TError,
      { data: WithdrawRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof withdraw>>,
  TError,
  { data: WithdrawRequest },
  TContext
> => {
  return useMutation(getWithdrawMutationOptions(options), queryClient);
};
export type queryWithdrawResponse200 = {
  data: ResultObject;
  status: 200;
};

export type queryWithdrawResponse400 = {
  data: ResultObject;
  status: 400;
};

export type queryWithdrawResponse401 = {
  data: WithdrawDetailResponse;
  status: 401;
};

export type queryWithdrawResponse405 = {
  data: ResultObject;
  status: 405;
};

export type queryWithdrawResponse500 = {
  data: ResultObject;
  status: 500;
};

export type queryWithdrawResponseSuccess = queryWithdrawResponse200 & {
  headers: Headers;
};
export type queryWithdrawResponseError = (
  | queryWithdrawResponse400
  | queryWithdrawResponse401
  | queryWithdrawResponse405
  | queryWithdrawResponse500
) & {
  headers: Headers;
};

export type queryWithdrawResponse =
  | queryWithdrawResponseSuccess
  | queryWithdrawResponseError;

export const getQueryWithdrawUrl = (orderNo: string) => {
  return `/api/userWallet/withdraw/${orderNo}`;
};

/**
 * 查询当前登录用户的提取订单详情。
 * @summary 查询提取订单详情
 */
export const queryWithdraw = async (
  orderNo: string,
  options?: RequestInit,
): Promise<queryWithdrawResponse> => {
  return appAxiosInstance<queryWithdrawResponse>(getQueryWithdrawUrl(orderNo), {
    ...options,
    method: 'GET',
  });
};

export const getQueryWithdrawQueryKey = (orderNo: string) => {
  return [`/api/userWallet/withdraw/${orderNo}`] as const;
};

export const getQueryWithdrawQueryOptions = <
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryWithdraw>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQueryWithdrawQueryKey(orderNo);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof queryWithdraw>>> = ({
    signal,
  }) => queryWithdraw(orderNo, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: orderNo !== null && orderNo !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryWithdraw>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryWithdrawQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryWithdraw>>
>;
export type QueryWithdrawQueryError = ResultObject | WithdrawDetailResponse;

export function useQueryWithdraw<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryWithdraw>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryWithdraw>>,
          TError,
          Awaited<ReturnType<typeof queryWithdraw>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryWithdraw<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryWithdraw>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryWithdraw>>,
          TError,
          Awaited<ReturnType<typeof queryWithdraw>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryWithdraw<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryWithdraw>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询提取订单详情
 */

export function useQueryWithdraw<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof queryWithdraw>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryWithdrawQueryOptions(orderNo, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getQueryWithdrawSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryWithdraw>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQueryWithdrawQueryKey(orderNo);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof queryWithdraw>>> = ({
    signal,
  }) => queryWithdraw(orderNo, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof queryWithdraw>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryWithdrawSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryWithdraw>>
>;
export type QueryWithdrawSuspenseQueryError =
  | ResultObject
  | WithdrawDetailResponse;

export function useQueryWithdrawSuspense<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryWithdraw>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryWithdrawSuspense<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryWithdraw>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryWithdrawSuspense<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryWithdraw>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 查询提取订单详情
 */

export function useQueryWithdrawSuspense<
  TData = Awaited<ReturnType<typeof queryWithdraw>>,
  TError = ResultObject | WithdrawDetailResponse,
>(
  orderNo: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof queryWithdraw>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryWithdrawSuspenseQueryOptions(orderNo, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
