/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Recommend API
 * StoryFun 推荐服务（首页「推荐」Tab）。
 * <p>
 * 主要接口：
 * <ul>
 *   <li><b>GET /api/recommend/feed</b> — 推荐流（支持未登录；首屏默认 10 条）</li>
 *   <li><b>GET /api/recommend/search</b> — 模糊搜索（支持未登录；keyword 必填，2~50 字）</li>
 *   <li><b>POST /api/recommend/dislike/{videoId}</b> — 不感兴趣（需登录；videoId = episodeId）</li>
 * </ul>
 * 标注「联调使用」的字段 / Debug 接口仅供联调排查。
 *
 * OpenAPI spec version: v0.5
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ExplainParams,
  ResultExplainResponse,
  ResultObject,
  ResultSnapshotDebugResponse,
  SnapshotParams,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type snapshotResponse200 = {
  data: ResultSnapshotDebugResponse;
  status: 200;
};

export type snapshotResponse400 = {
  data: ResultObject;
  status: 400;
};

export type snapshotResponseSuccess = snapshotResponse200 & {
  headers: Headers;
};
export type snapshotResponseError = snapshotResponse400 & {
  headers: Headers;
};

export type snapshotResponse = snapshotResponseSuccess | snapshotResponseError;

export const getSnapshotUrl = (params: SnapshotParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/recommend/debug/snapshot?${stringifiedParams}`
    : `/api/recommend/debug/snapshot`;
};

/**
 * @summary 联调使用：查看当前快照
 */
export const snapshot = async (
  params: SnapshotParams,
  options?: RequestInit,
): Promise<snapshotResponse> => {
  return appAxiosInstance<snapshotResponse>(getSnapshotUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSnapshotQueryKey = (params?: SnapshotParams) => {
  return [
    `/api/recommend/debug/snapshot`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSnapshotQueryOptions = <
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof snapshot>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSnapshotQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof snapshot>>> = ({
    signal,
  }) => snapshot(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof snapshot>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SnapshotQueryResult = NonNullable<
  Awaited<ReturnType<typeof snapshot>>
>;
export type SnapshotQueryError = ResultObject;

export function useSnapshot<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof snapshot>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof snapshot>>,
          TError,
          Awaited<ReturnType<typeof snapshot>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSnapshot<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof snapshot>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof snapshot>>,
          TError,
          Awaited<ReturnType<typeof snapshot>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSnapshot<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof snapshot>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 联调使用：查看当前快照
 */

export function useSnapshot<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof snapshot>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSnapshotQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getSnapshotSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof snapshot>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSnapshotQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof snapshot>>> = ({
    signal,
  }) => snapshot(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof snapshot>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SnapshotSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof snapshot>>
>;
export type SnapshotSuspenseQueryError = ResultObject;

export function useSnapshotSuspense<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof snapshot>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSnapshotSuspense<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof snapshot>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSnapshotSuspense<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof snapshot>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 联调使用：查看当前快照
 */

export function useSnapshotSuspense<
  TData = Awaited<ReturnType<typeof snapshot>>,
  TError = ResultObject,
>(
  params: SnapshotParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof snapshot>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSnapshotSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type explainResponse200 = {
  data: ResultExplainResponse;
  status: 200;
};

export type explainResponse400 = {
  data: ResultObject;
  status: 400;
};

export type explainResponseSuccess = explainResponse200 & {
  headers: Headers;
};
export type explainResponseError = explainResponse400 & {
  headers: Headers;
};

export type explainResponse = explainResponseSuccess | explainResponseError;

export const getExplainUrl = (params: ExplainParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/recommend/debug/explain?${stringifiedParams}`
    : `/api/recommend/debug/explain`;
};

/**
 * @summary 联调使用：打分解释（episodeId 优先，未传则取该剧首集）
 */
export const explain = async (
  params: ExplainParams,
  options?: RequestInit,
): Promise<explainResponse> => {
  return appAxiosInstance<explainResponse>(getExplainUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getExplainQueryKey = (params?: ExplainParams) => {
  return [`/api/recommend/debug/explain`, ...(params ? [params] : [])] as const;
};

export const getExplainQueryOptions = <
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof explain>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExplainQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof explain>>> = ({
    signal,
  }) => explain(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof explain>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExplainQueryResult = NonNullable<
  Awaited<ReturnType<typeof explain>>
>;
export type ExplainQueryError = ResultObject;

export function useExplain<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof explain>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof explain>>,
          TError,
          Awaited<ReturnType<typeof explain>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExplain<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof explain>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof explain>>,
          TError,
          Awaited<ReturnType<typeof explain>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExplain<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof explain>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 联调使用：打分解释（episodeId 优先，未传则取该剧首集）
 */

export function useExplain<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof explain>>, TError, TData>
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExplainQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getExplainSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof explain>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExplainQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof explain>>> = ({
    signal,
  }) => explain(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof explain>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExplainSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof explain>>
>;
export type ExplainSuspenseQueryError = ResultObject;

export function useExplainSuspense<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof explain>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExplainSuspense<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof explain>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExplainSuspense<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof explain>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 联调使用：打分解释（episodeId 优先，未传则取该剧首集）
 */

export function useExplainSuspense<
  TData = Awaited<ReturnType<typeof explain>>,
  TError = ResultObject,
>(
  params: ExplainParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof explain>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExplainSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
