/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  RecalculateHeatForTest200,
  RecalculateHeatForTestParams,
  ResetHeatEnvRequest,
  ResultObject,
  ResultResetHeatEnvResponse,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type recalculateHeatForTestResponse200 = {
  data: RecalculateHeatForTest200;
  status: 200;
};

export type recalculateHeatForTestResponse400 = {
  data: ResultObject;
  status: 400;
};

export type recalculateHeatForTestResponseSuccess =
  recalculateHeatForTestResponse200 & {
    headers: Headers;
  };
export type recalculateHeatForTestResponseError =
  recalculateHeatForTestResponse400 & {
    headers: Headers;
  };

export type recalculateHeatForTestResponse =
  | recalculateHeatForTestResponseSuccess
  | recalculateHeatForTestResponseError;

export const getRecalculateHeatForTestUrl = (
  dramaId: number,
  params: RecalculateHeatForTestParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/public/dramas/${dramaId}/heat/test-recalculate?${stringifiedParams}`
    : `/api/mini-drama/public/dramas/${dramaId}/heat/test-recalculate`;
};

/**
 * 先向 stat_drama_heat_behavior_daily 插入行为数据，再调用本接口触发当日重算。每次只能处理一个日期。
 * @summary 手动重算指定短剧指定日期的热度并广播下游（需先 SQL 插入行为数据）
 */
export const recalculateHeatForTest = async (
  dramaId: number,
  params: RecalculateHeatForTestParams,
  options?: RequestInit,
): Promise<recalculateHeatForTestResponse> => {
  return appAxiosInstance<recalculateHeatForTestResponse>(
    getRecalculateHeatForTestUrl(dramaId, params),
    {
      ...options,
      method: 'POST',
    },
  );
};

export const getRecalculateHeatForTestMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recalculateHeatForTest>>,
    TError,
    { dramaId: number; params: RecalculateHeatForTestParams },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recalculateHeatForTest>>,
  TError,
  { dramaId: number; params: RecalculateHeatForTestParams },
  TContext
> => {
  const mutationKey = ['recalculateHeatForTest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recalculateHeatForTest>>,
    { dramaId: number; params: RecalculateHeatForTestParams }
  > = (props) => {
    const { dramaId, params } = props ?? {};

    return recalculateHeatForTest(dramaId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecalculateHeatForTestMutationResult = NonNullable<
  Awaited<ReturnType<typeof recalculateHeatForTest>>
>;

export type RecalculateHeatForTestMutationError = ResultObject;

/**
 * @summary 手动重算指定短剧指定日期的热度并广播下游（需先 SQL 插入行为数据）
 */
export const useRecalculateHeatForTest = <
  TError = ResultObject,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recalculateHeatForTest>>,
      TError,
      { dramaId: number; params: RecalculateHeatForTestParams },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recalculateHeatForTest>>,
  TError,
  { dramaId: number; params: RecalculateHeatForTestParams },
  TContext
> => {
  return useMutation(
    getRecalculateHeatForTestMutationOptions(options),
    queryClient,
  );
};
export type resetHeatEnvResponse200 = {
  data: ResultResetHeatEnvResponse;
  status: 200;
};

export type resetHeatEnvResponse400 = {
  data: ResultObject;
  status: 400;
};

export type resetHeatEnvResponseSuccess = resetHeatEnvResponse200 & {
  headers: Headers;
};
export type resetHeatEnvResponseError = resetHeatEnvResponse400 & {
  headers: Headers;
};

export type resetHeatEnvResponse =
  | resetHeatEnvResponseSuccess
  | resetHeatEnvResponseError;

export const getResetHeatEnvUrl = () => {
  return `/api/mini-drama/public/dramas/heat/clean-ip-device`;
};

/**
 * 删除该 user_id 在 stat_heat_anti_fraud_audit / stat_drama_heat_behavior_daily / stat_drama_heat_behavior_event / stat_heat_user_device_ip 四张表的数据; 并按 stat_heat_user_device_ip 反查该用户出现过的 device_id / client_ip, 删除对应反作弊 Redis key。无二次确认。
 * @summary 清空指定 user_id 在热度系统的全部数据(仅当前部署环境, 需登录)
 */
export const resetHeatEnv = async (
  resetHeatEnvRequest: ResetHeatEnvRequest,
  options?: RequestInit,
): Promise<resetHeatEnvResponse> => {
  return appAxiosInstance<resetHeatEnvResponse>(getResetHeatEnvUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resetHeatEnvRequest),
  });
};

export const getResetHeatEnvMutationOptions = <
  TError = ResultObject,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetHeatEnv>>,
    TError,
    { data: ResetHeatEnvRequest },
    TContext
  >;
  request?: SecondParameter<typeof appAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetHeatEnv>>,
  TError,
  { data: ResetHeatEnvRequest },
  TContext
> => {
  const mutationKey = ['resetHeatEnv'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetHeatEnv>>,
    { data: ResetHeatEnvRequest }
  > = (props) => {
    const { data } = props ?? {};

    return resetHeatEnv(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetHeatEnvMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetHeatEnv>>
>;
export type ResetHeatEnvMutationBody = ResetHeatEnvRequest;
export type ResetHeatEnvMutationError = ResultObject;

/**
 * @summary 清空指定 user_id 在热度系统的全部数据(仅当前部署环境, 需登录)
 */
export const useResetHeatEnv = <TError = ResultObject, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resetHeatEnv>>,
      TError,
      { data: ResetHeatEnvRequest },
      TContext
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof resetHeatEnv>>,
  TError,
  { data: ResetHeatEnvRequest },
  TContext
> => {
  return useMutation(getResetHeatEnvMutationOptions(options), queryClient);
};
