/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Mini Drama Service API
 * Mini Drama Platform
 * OpenAPI spec version: v1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import { appAxiosInstance } from '../../../appRequest';
import type {
  ListPublicCollectionsParams,
  PageDtoCollectionListItemResponse,
  ResultObject,
} from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listPublicCollectionsResponse200 = {
  data: PageDtoCollectionListItemResponse;
  status: 200;
};

export type listPublicCollectionsResponse400 = {
  data: ResultObject;
  status: 400;
};

export type listPublicCollectionsResponseSuccess =
  listPublicCollectionsResponse200 & {
    headers: Headers;
  };
export type listPublicCollectionsResponseError =
  listPublicCollectionsResponse400 & {
    headers: Headers;
  };

export type listPublicCollectionsResponse =
  | listPublicCollectionsResponseSuccess
  | listPublicCollectionsResponseError;

export const getListPublicCollectionsUrl = (
  params?: ListPublicCollectionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/mini-drama/public/collections?${stringifiedParams}`
    : `/api/mini-drama/public/collections`;
};

/**
 * @summary [无鉴权]合集列表
 */
export const listPublicCollections = async (
  params?: ListPublicCollectionsParams,
  options?: RequestInit,
): Promise<listPublicCollectionsResponse> => {
  return appAxiosInstance<listPublicCollectionsResponse>(
    getListPublicCollectionsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getListPublicCollectionsQueryKey = (
  params?: ListPublicCollectionsParams,
) => {
  return [
    `/api/mini-drama/public/collections`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListPublicCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListPublicCollectionsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPublicCollections>>
  > = ({ signal }) =>
    listPublicCollections(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPublicCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPublicCollectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPublicCollections>>
>;
export type ListPublicCollectionsQueryError = ResultObject;

export function useListPublicCollections<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params: undefined | ListPublicCollectionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicCollections>>,
          TError,
          Awaited<ReturnType<typeof listPublicCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicCollections<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicCollections>>,
          TError,
          Awaited<ReturnType<typeof listPublicCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicCollections<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]合集列表
 */

export function useListPublicCollections<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPublicCollectionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getListPublicCollectionsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListPublicCollectionsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPublicCollections>>
  > = ({ signal }) =>
    listPublicCollections(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof listPublicCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPublicCollectionsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPublicCollections>>
>;
export type ListPublicCollectionsSuspenseQueryError = ResultObject;

export function useListPublicCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params: undefined | ListPublicCollectionsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublicCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [无鉴权]合集列表
 */

export function useListPublicCollectionsSuspense<
  TData = Awaited<ReturnType<typeof listPublicCollections>>,
  TError = ResultObject,
>(
  params?: ListPublicCollectionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublicCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof appAxiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPublicCollectionsSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
