/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SocialBindRouteImport } from './routes/social-bind'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NarratorRouteImport } from './routes/narrator'
import { Route as GameRouteImport } from './routes/game'
import { Route as EditRouteImport } from './routes/edit'
import { Route as DramasRouteImport } from './routes/dramas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreationManagementRouteImport } from './routes/creation-management'
import { Route as CreateShortVideoRouteImport } from './routes/create-short-video'
import { Route as CreateRouteImport } from './routes/create'
import { Route as R1011homeRouteImport } from './routes/1011home'
import { Route as R1011RouteImport } from './routes/1011'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as PlayRouteRouteImport } from './routes/play/route'
import { Route as InviteRouteRouteImport } from './routes/invite/route'
import { Route as IncomeRouteRouteImport } from './routes/income/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as InviteIndexRouteImport } from './routes/invite/index'
import { Route as IncomeIndexRouteImport } from './routes/income/index'
import { Route as ActorIndexRouteImport } from './routes/actor/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as PlaySearchRouteImport } from './routes/play/search'
import { Route as NarratorCreateActorRouteImport } from './routes/narrator.create-actor'
import { Route as InviteRecordsRouteImport } from './routes/invite/records'
import { Route as ActorActorIdRouteImport } from './routes/actor/$actorId'
import { Route as PlayDramaIdRouteRouteImport } from './routes/play/$dramaId/route'
import { Route as PlayDramaIdIndexRouteImport } from './routes/play/$dramaId/index'
import { Route as PlayDramaIdWatchRouteImport } from './routes/play/$dramaId/watch'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialBindRoute = SocialBindRouteImport.update({
  id: '/social-bind',
  path: '/social-bind',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NarratorRoute = NarratorRouteImport.update({
  id: '/narrator',
  path: '/narrator',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasRoute = DramasRouteImport.update({
  id: '/dramas',
  path: '/dramas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationManagementRoute = CreationManagementRouteImport.update({
  id: '/creation-management',
  path: '/creation-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateShortVideoRoute = CreateShortVideoRouteImport.update({
  id: '/create-short-video',
  path: '/create-short-video',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const R1011homeRoute = R1011homeRouteImport.update({
  id: '/1011home',
  path: '/1011home',
  getParentRoute: () => rootRouteImport,
} as any)
const R1011Route = R1011RouteImport.update({
  id: '/1011',
  path: '/1011',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRouteRoute = PlayRouteRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRouteRoute = InviteRouteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRouteRoute = IncomeRouteRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRouteRoute,
} as any)
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InviteRouteRoute,
} as any)
const IncomeIndexRoute = IncomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncomeRouteRoute,
} as any)
const ActorIndexRoute = ActorIndexRouteImport.update({
  id: '/actor/',
  path: '/actor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const PlaySearchRoute = PlaySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PlayRouteRoute,
} as any)
const NarratorCreateActorRoute = NarratorCreateActorRouteImport.update({
  id: '/create-actor',
  path: '/create-actor',
  getParentRoute: () => NarratorRoute,
} as any)
const InviteRecordsRoute = InviteRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => InviteRouteRoute,
} as any)
const ActorActorIdRoute = ActorActorIdRouteImport.update({
  id: '/actor/$actorId',
  path: '/actor/$actorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDramaIdRouteRoute = PlayDramaIdRouteRouteImport.update({
  id: '/$dramaId',
  path: '/$dramaId',
  getParentRoute: () => PlayRouteRoute,
} as any)
const PlayDramaIdIndexRoute = PlayDramaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayDramaIdRouteRoute,
} as any)
const PlayDramaIdWatchRoute = PlayDramaIdWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => PlayDramaIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/income': typeof IncomeRouteRouteWithChildren
  '/invite': typeof InviteRouteRouteWithChildren
  '/play': typeof PlayRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/1011': typeof R1011Route
  '/1011home': typeof R1011homeRoute
  '/create': typeof CreateRoute
  '/create-short-video': typeof CreateShortVideoRoute
  '/creation-management': typeof CreationManagementRoute
  '/dashboard': typeof DashboardRoute
  '/dramas': typeof DramasRoute
  '/edit': typeof EditRoute
  '/game': typeof GameRoute
  '/narrator': typeof NarratorRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/social-bind': typeof SocialBindRoute
  '/terms': typeof TermsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/play/$dramaId': typeof PlayDramaIdRouteRouteWithChildren
  '/actor/$actorId': typeof ActorActorIdRoute
  '/invite/records': typeof InviteRecordsRoute
  '/narrator/create-actor': typeof NarratorCreateActorRoute
  '/play/search': typeof PlaySearchRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/actor/': typeof ActorIndexRoute
  '/income/': typeof IncomeIndexRoute
  '/invite/': typeof InviteIndexRoute
  '/play/': typeof PlayIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/play/$dramaId/watch': typeof PlayDramaIdWatchRoute
  '/play/$dramaId/': typeof PlayDramaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1011': typeof R1011Route
  '/1011home': typeof R1011homeRoute
  '/create': typeof CreateRoute
  '/create-short-video': typeof CreateShortVideoRoute
  '/creation-management': typeof CreationManagementRoute
  '/dashboard': typeof DashboardRoute
  '/dramas': typeof DramasRoute
  '/edit': typeof EditRoute
  '/game': typeof GameRoute
  '/narrator': typeof NarratorRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/social-bind': typeof SocialBindRoute
  '/terms': typeof TermsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/actor/$actorId': typeof ActorActorIdRoute
  '/invite/records': typeof InviteRecordsRoute
  '/narrator/create-actor': typeof NarratorCreateActorRoute
  '/play/search': typeof PlaySearchRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/actor': typeof ActorIndexRoute
  '/income': typeof IncomeIndexRoute
  '/invite': typeof InviteIndexRoute
  '/play': typeof PlayIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/play/$dramaId/watch': typeof PlayDramaIdWatchRoute
  '/play/$dramaId': typeof PlayDramaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/income': typeof IncomeRouteRouteWithChildren
  '/invite': typeof InviteRouteRouteWithChildren
  '/play': typeof PlayRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/1011': typeof R1011Route
  '/1011home': typeof R1011homeRoute
  '/create': typeof CreateRoute
  '/create-short-video': typeof CreateShortVideoRoute
  '/creation-management': typeof CreationManagementRoute
  '/dashboard': typeof DashboardRoute
  '/dramas': typeof DramasRoute
  '/edit': typeof EditRoute
  '/game': typeof GameRoute
  '/narrator': typeof NarratorRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/social-bind': typeof SocialBindRoute
  '/terms': typeof TermsRoute
  '/whitepaper': typeof WhitepaperRoute
  '/play/$dramaId': typeof PlayDramaIdRouteRouteWithChildren
  '/actor/$actorId': typeof ActorActorIdRoute
  '/invite/records': typeof InviteRecordsRoute
  '/narrator/create-actor': typeof NarratorCreateActorRoute
  '/play/search': typeof PlaySearchRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/actor/': typeof ActorIndexRoute
  '/income/': typeof IncomeIndexRoute
  '/invite/': typeof InviteIndexRoute
  '/play/': typeof PlayIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/play/$dramaId/watch': typeof PlayDramaIdWatchRoute
  '/play/$dramaId/': typeof PlayDramaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/income'
    | '/invite'
    | '/play'
    | '/profile'
    | '/1011'
    | '/1011home'
    | '/create'
    | '/create-short-video'
    | '/creation-management'
    | '/dashboard'
    | '/dramas'
    | '/edit'
    | '/game'
    | '/narrator'
    | '/privacy'
    | '/search'
    | '/social-bind'
    | '/terms'
    | '/whitepaper'
    | '/play/$dramaId'
    | '/actor/$actorId'
    | '/invite/records'
    | '/narrator/create-actor'
    | '/play/search'
    | '/profile/$userId'
    | '/actor/'
    | '/income/'
    | '/invite/'
    | '/play/'
    | '/profile/'
    | '/play/$dramaId/watch'
    | '/play/$dramaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1011'
    | '/1011home'
    | '/create'
    | '/create-short-video'
    | '/creation-management'
    | '/dashboard'
    | '/dramas'
    | '/edit'
    | '/game'
    | '/narrator'
    | '/privacy'
    | '/search'
    | '/social-bind'
    | '/terms'
    | '/whitepaper'
    | '/actor/$actorId'
    | '/invite/records'
    | '/narrator/create-actor'
    | '/play/search'
    | '/profile/$userId'
    | '/actor'
    | '/income'
    | '/invite'
    | '/play'
    | '/profile'
    | '/play/$dramaId/watch'
    | '/play/$dramaId'
  id:
    | '__root__'
    | '/'
    | '/income'
    | '/invite'
    | '/play'
    | '/profile'
    | '/1011'
    | '/1011home'
    | '/create'
    | '/create-short-video'
    | '/creation-management'
    | '/dashboard'
    | '/dramas'
    | '/edit'
    | '/game'
    | '/narrator'
    | '/privacy'
    | '/search'
    | '/social-bind'
    | '/terms'
    | '/whitepaper'
    | '/play/$dramaId'
    | '/actor/$actorId'
    | '/invite/records'
    | '/narrator/create-actor'
    | '/play/search'
    | '/profile/$userId'
    | '/actor/'
    | '/income/'
    | '/invite/'
    | '/play/'
    | '/profile/'
    | '/play/$dramaId/watch'
    | '/play/$dramaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncomeRouteRoute: typeof IncomeRouteRouteWithChildren
  InviteRouteRoute: typeof InviteRouteRouteWithChildren
  PlayRouteRoute: typeof PlayRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  R1011Route: typeof R1011Route
  R1011homeRoute: typeof R1011homeRoute
  CreateRoute: typeof CreateRoute
  CreateShortVideoRoute: typeof CreateShortVideoRoute
  CreationManagementRoute: typeof CreationManagementRoute
  DashboardRoute: typeof DashboardRoute
  DramasRoute: typeof DramasRoute
  EditRoute: typeof EditRoute
  GameRoute: typeof GameRoute
  NarratorRoute: typeof NarratorRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SocialBindRoute: typeof SocialBindRoute
  TermsRoute: typeof TermsRoute
  WhitepaperRoute: typeof WhitepaperRoute
  ActorActorIdRoute: typeof ActorActorIdRoute
  ActorIndexRoute: typeof ActorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-bind': {
      id: '/social-bind'
      path: '/social-bind'
      fullPath: '/social-bind'
      preLoaderRoute: typeof SocialBindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narrator': {
      id: '/narrator'
      path: '/narrator'
      fullPath: '/narrator'
      preLoaderRoute: typeof NarratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas': {
      id: '/dramas'
      path: '/dramas'
      fullPath: '/dramas'
      preLoaderRoute: typeof DramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-management': {
      id: '/creation-management'
      path: '/creation-management'
      fullPath: '/creation-management'
      preLoaderRoute: typeof CreationManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-short-video': {
      id: '/create-short-video'
      path: '/create-short-video'
      fullPath: '/create-short-video'
      preLoaderRoute: typeof CreateShortVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1011home': {
      id: '/1011home'
      path: '/1011home'
      fullPath: '/1011home'
      preLoaderRoute: typeof R1011homeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1011': {
      id: '/1011'
      path: '/1011'
      fullPath: '/1011'
      preLoaderRoute: typeof R1011RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/invite/': {
      id: '/invite/'
      path: '/'
      fullPath: '/invite/'
      preLoaderRoute: typeof InviteIndexRouteImport
      parentRoute: typeof InviteRouteRoute
    }
    '/income/': {
      id: '/income/'
      path: '/'
      fullPath: '/income/'
      preLoaderRoute: typeof IncomeIndexRouteImport
      parentRoute: typeof IncomeRouteRoute
    }
    '/actor/': {
      id: '/actor/'
      path: '/actor'
      fullPath: '/actor/'
      preLoaderRoute: typeof ActorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/play/search': {
      id: '/play/search'
      path: '/search'
      fullPath: '/play/search'
      preLoaderRoute: typeof PlaySearchRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/narrator/create-actor': {
      id: '/narrator/create-actor'
      path: '/create-actor'
      fullPath: '/narrator/create-actor'
      preLoaderRoute: typeof NarratorCreateActorRouteImport
      parentRoute: typeof NarratorRoute
    }
    '/invite/records': {
      id: '/invite/records'
      path: '/records'
      fullPath: '/invite/records'
      preLoaderRoute: typeof InviteRecordsRouteImport
      parentRoute: typeof InviteRouteRoute
    }
    '/actor/$actorId': {
      id: '/actor/$actorId'
      path: '/actor/$actorId'
      fullPath: '/actor/$actorId'
      preLoaderRoute: typeof ActorActorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$dramaId': {
      id: '/play/$dramaId'
      path: '/$dramaId'
      fullPath: '/play/$dramaId'
      preLoaderRoute: typeof PlayDramaIdRouteRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/play/$dramaId/': {
      id: '/play/$dramaId/'
      path: '/'
      fullPath: '/play/$dramaId/'
      preLoaderRoute: typeof PlayDramaIdIndexRouteImport
      parentRoute: typeof PlayDramaIdRouteRoute
    }
    '/play/$dramaId/watch': {
      id: '/play/$dramaId/watch'
      path: '/watch'
      fullPath: '/play/$dramaId/watch'
      preLoaderRoute: typeof PlayDramaIdWatchRouteImport
      parentRoute: typeof PlayDramaIdRouteRoute
    }
  }
}

interface IncomeRouteRouteChildren {
  IncomeIndexRoute: typeof IncomeIndexRoute
}

const IncomeRouteRouteChildren: IncomeRouteRouteChildren = {
  IncomeIndexRoute: IncomeIndexRoute,
}

const IncomeRouteRouteWithChildren = IncomeRouteRoute._addFileChildren(
  IncomeRouteRouteChildren,
)

interface InviteRouteRouteChildren {
  InviteRecordsRoute: typeof InviteRecordsRoute
  InviteIndexRoute: typeof InviteIndexRoute
}

const InviteRouteRouteChildren: InviteRouteRouteChildren = {
  InviteRecordsRoute: InviteRecordsRoute,
  InviteIndexRoute: InviteIndexRoute,
}

const InviteRouteRouteWithChildren = InviteRouteRoute._addFileChildren(
  InviteRouteRouteChildren,
)

interface PlayDramaIdRouteRouteChildren {
  PlayDramaIdWatchRoute: typeof PlayDramaIdWatchRoute
  PlayDramaIdIndexRoute: typeof PlayDramaIdIndexRoute
}

const PlayDramaIdRouteRouteChildren: PlayDramaIdRouteRouteChildren = {
  PlayDramaIdWatchRoute: PlayDramaIdWatchRoute,
  PlayDramaIdIndexRoute: PlayDramaIdIndexRoute,
}

const PlayDramaIdRouteRouteWithChildren =
  PlayDramaIdRouteRoute._addFileChildren(PlayDramaIdRouteRouteChildren)

interface PlayRouteRouteChildren {
  PlayDramaIdRouteRoute: typeof PlayDramaIdRouteRouteWithChildren
  PlaySearchRoute: typeof PlaySearchRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteRouteChildren: PlayRouteRouteChildren = {
  PlayDramaIdRouteRoute: PlayDramaIdRouteRouteWithChildren,
  PlaySearchRoute: PlaySearchRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteRouteWithChildren = PlayRouteRoute._addFileChildren(
  PlayRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface NarratorRouteChildren {
  NarratorCreateActorRoute: typeof NarratorCreateActorRoute
}

const NarratorRouteChildren: NarratorRouteChildren = {
  NarratorCreateActorRoute: NarratorCreateActorRoute,
}

const NarratorRouteWithChildren = NarratorRoute._addFileChildren(
  NarratorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncomeRouteRoute: IncomeRouteRouteWithChildren,
  InviteRouteRoute: InviteRouteRouteWithChildren,
  PlayRouteRoute: PlayRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  R1011Route: R1011Route,
  R1011homeRoute: R1011homeRoute,
  CreateRoute: CreateRoute,
  CreateShortVideoRoute: CreateShortVideoRoute,
  CreationManagementRoute: CreationManagementRoute,
  DashboardRoute: DashboardRoute,
  DramasRoute: DramasRoute,
  EditRoute: EditRoute,
  GameRoute: GameRoute,
  NarratorRoute: NarratorRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SocialBindRoute: SocialBindRoute,
  TermsRoute: TermsRoute,
  WhitepaperRoute: WhitepaperRoute,
  ActorActorIdRoute: ActorActorIdRoute,
  ActorIndexRoute: ActorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
